import type { Payload } from 'payload'

export interface DepartureSlotSeedDef {
  departureId: string
  experienceSlug: string
  date: string // YYYY-MM-DD
  startTime: string // HH:mm in Africa/Cairo
  capacityTotal: number // L'Aube contracted commercial allocation
  capacityReserved: number
  capacitySold: number
  capacityAvailable: number
  version: number
  status: 'available' | 'sold_out' | 'blacked_out' | 'cancelled'
  priceOverrideEGP?: number | null
}

/**
 * Master List of 86 Verified Discrete Departure Slots across the 7 Scheduled Fixed-Date Packages.
 * High Season: October 2026 – March 2027.
 * Dynamic IANA Timezone: Africa/Cairo (UTC+3 pre-Oct 30, UTC+2 post-Oct 30, 2026).
 * Zero algorithmic recurrence logic (discrete explicit inventory).
 */
export const CANONICAL_DEPARTURE_SLOTS: DepartureSlotSeedDef[] = [
  // =========================================================================
  // 1. The Oberoi Zahra Upper Egypt Sovereign Cruise (5D/4N) — EXP-NL-01 (13 Slots)
  // Tuesday Departures from Luxor (12:00 PM) | L'Aube Allocation: 14 Guests (Ship Total: 54)
  // =========================================================================
  {
    departureId: 'DEP-EXP-NL-01-20261006',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-10-06',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20261020',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-10-20',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20261110',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-11-10',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20261124',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-11-24',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20261201',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-12-01',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20261215',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-12-15',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20261229',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2026-12-29',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20270112',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2027-01-12',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20270126',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2027-01-26',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20270209',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2027-02-09',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20270223',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2027-02-23',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20270309',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2027-03-09',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-01-20270323',
    experienceSlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    date: '2027-03-23',
    startTime: '12:00',
    capacityTotal: 14,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 14,
    version: 1,
    status: 'available',
  },

  // =========================================================================
  // 2. Royal Upper Egypt Heritage: Winter Palace & Sonesta (6D/5N) — EXP-NL-02 (13 Slots)
  // Sunday Package Start from Luxor Winter Palace (14:00) | L'Aube Allocation: 16 Guests (Ship Total: 104)
  // =========================================================================
  {
    departureId: 'DEP-EXP-NL-02-20261011',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2026-10-11',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20261025',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2026-10-25',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20261108',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2026-11-08',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20261122',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2026-11-22',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20261206',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2026-12-06',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20261220',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2026-12-20',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270103',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-01-03',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270117',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-01-17',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270131',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-01-31',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270214',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-02-14',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270228',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-02-28',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270314',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-03-14',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-NL-02-20270328',
    experienceSlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    date: '2027-03-28',
    startTime: '14:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },

  // =========================================================================
  // 3. Classical Nile and Pharaonic Odyssey (7D/6N) — EXP-EG-03 (12 Slots)
  // Friday Departures from Cairo (15:00) | L'Aube Allocation: 16 Guests (8 Palace Rooms)
  // =========================================================================
  {
    departureId: 'DEP-EXP-EG-03-20261009',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2026-10-09',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20261023',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2026-10-23',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20261106',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2026-11-06',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20261120',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2026-11-20',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20261204',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2026-12-04',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20261218',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2026-12-18',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20270108',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2027-01-08',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20270122',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2027-01-22',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20270205',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2027-02-05',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20270219',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2027-02-19',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20270305',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2027-03-05',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-03-20270319',
    experienceSlug: 'classical-nile-pharaonic-odyssey-7d',
    date: '2027-03-19',
    startTime: '15:00',
    capacityTotal: 16,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 16,
    version: 1,
    status: 'available',
  },

  // =========================================================================
  // 4. Grand Egypt Imperial Heritage Loop (10D/9N) — EXP-EG-04 (12 Slots)
  // Saturday Departures from Cairo (15:00) | L'Aube Allocation: 12 Guests (6 Suites)
  // =========================================================================
  {
    departureId: 'DEP-EXP-EG-04-20261003',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2026-10-03',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20261017',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2026-10-17',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20261107',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2026-11-07',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20261121',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2026-11-21',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20261205',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2026-12-05',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20261219',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2026-12-19',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20270109',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2027-01-09',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20270123',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2027-01-23',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20270206',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2027-02-06',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20270220',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2027-02-20',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20270306',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2027-03-06',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-EG-04-20270320',
    experienceSlug: 'grand-egypt-imperial-loop-10d',
    date: '2027-03-20',
    startTime: '15:00',
    capacityTotal: 12,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 12,
    version: 1,
    status: 'available',
  },

  // =========================================================================
  // 5. Pharaonic Heritage & Arabian Desert Elegance: Cairo to Dubai (7D/6N) — EXP-INT-01 (12 Slots)
  // Saturday Departures from Cairo (15:00) | L'Aube Allocation: 10 Guests (5 Suites)
  // =========================================================================
  {
    departureId: 'DEP-EXP-INT-01-20261010',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2026-10-10',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20261024',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2026-10-24',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20261114',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2026-11-14',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20261128',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2026-11-28',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20261212',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2026-12-12',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20261226',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2026-12-26',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20270109',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2027-01-09',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20270123',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2027-01-23',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20270213',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2027-02-13',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20270227',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2027-02-27',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20270313',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2027-03-13',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-01-20270327',
    experienceSlug: 'pharaonic-heritage-arabian-desert-elegance-cairo-dubai',
    date: '2027-03-27',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },

  // =========================================================================
  // 6. Empires of Elegance: Cairo and Paris Palace Odyssey (8D/7N) — EXP-INT-02 (12 Slots)
  // Sunday Departures from Cairo (15:00) | L'Aube Allocation: 10 Guests (5 Palace Suites)
  // =========================================================================
  {
    departureId: 'DEP-EXP-INT-02-20261004',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2026-10-04',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20261018',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2026-10-18',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20261101',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2026-11-01',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20261115',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2026-11-15',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20261206',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2026-12-06',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20261220',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2026-12-20',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20270110',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2027-01-10',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20270124',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2027-01-24',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20270207',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2027-02-07',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20270221',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2027-02-21',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20270307',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2027-03-07',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-02-20270321',
    experienceSlug: 'empires-of-elegance-cairo-paris-palace-odyssey-8d',
    date: '2027-03-21',
    startTime: '15:00',
    capacityTotal: 10,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 10,
    version: 1,
    status: 'available',
  },

  // =========================================================================
  // 7. The Transcontinental Grand Horizon: Cairo, Dubai & Paris (11D/10N) — EXP-INT-03 (12 Slots)
  // Thursday Departures from Cairo (15:00) | L'Aube Allocation: 8 Guests (4 Suites)
  // =========================================================================
  {
    departureId: 'DEP-EXP-INT-03-20261008',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2026-10-08',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20261022',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2026-10-22',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20261105',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2026-11-05',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20261119',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2026-11-19',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20261203',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2026-12-03',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20261217',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2026-12-17',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20270114',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2027-01-14',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20270128',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2027-01-28',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20270211',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2027-02-11',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20270225',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2027-02-25',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20270311',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2027-03-11',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
  {
    departureId: 'DEP-EXP-INT-03-20270325',
    experienceSlug: 'transcontinental-grand-horizon-cairo-dubai-paris-11d',
    date: '2027-03-25',
    startTime: '15:00',
    capacityTotal: 8,
    capacityReserved: 0,
    capacitySold: 0,
    capacityAvailable: 8,
    version: 1,
    status: 'available',
  },
]

export interface SeedDepartureSlotsResult {
  totalProcessed: number
  totalCreated: number
  totalUpdated: number
  slotsByExperience: Record<string, number>
}

/**
 * Deterministically seed the 86 verified departure slots into PostgreSQL.
 * Strict idempotent upsert matching by unique `departureId`.
 */
export async function seedDepartureSlots(
  payload: Payload,
  experienceDocsMap?: Record<string, any>,
): Promise<SeedDepartureSlotsResult> {
  console.log('   🚢 Seeding Operational Departure Slots (Phase 8: 86 Discrete Slots)...')

  // If experience map not provided, resolve from database
  let expMap = experienceDocsMap
  if (!expMap || Object.keys(expMap).length === 0) {
    const expRes = await payload.find({
      collection: 'experiences',
      limit: 100,
    })
    expMap = {}
    for (const exp of expRes.docs) {
      expMap[exp.slug] = exp
    }
  }

  let totalCreated = 0
  let totalUpdated = 0
  const slotsByExperience: Record<string, number> = {}

  for (const slotDef of CANONICAL_DEPARTURE_SLOTS) {
    const expDoc = expMap[slotDef.experienceSlug]
    if (!expDoc) {
      throw new Error(
        `[seedDepartureSlots] Target Experience with slug '${slotDef.experienceSlug}' not found in database.`,
      )
    }

    const slotPayloadData: Record<string, any> = {
      departureId: slotDef.departureId,
      experience: expDoc.id,
      date: slotDef.date,
      startTime: slotDef.startTime,
      capacityTotal: slotDef.capacityTotal,
      capacityReserved: slotDef.capacityReserved,
      capacitySold: slotDef.capacitySold,
      capacityAvailable: slotDef.capacityAvailable,
      version: slotDef.version,
      status: slotDef.status,
    }

    if (slotDef.priceOverrideEGP !== undefined && slotDef.priceOverrideEGP !== null) {
      slotPayloadData.priceOverrideEGP = slotDef.priceOverrideEGP
    }

    // Deterministic Idempotent Upsert by unique departureId
    const existing = await payload.find({
      collection: 'departure-slots',
      where: {
        departureId: { equals: slotDef.departureId },
      },
      limit: 1,
    })

    if (existing.docs.length > 0) {
      const existingId = existing.docs[0].id
      await payload.update({
        collection: 'departure-slots',
        id: existingId,
        data: slotPayloadData,
      })
      totalUpdated++
    } else {
      await payload.create({
        collection: 'departure-slots',
        data: slotPayloadData as any,
      })
      totalCreated++
    }

    slotsByExperience[slotDef.experienceSlug] = (slotsByExperience[slotDef.experienceSlug] || 0) + 1
  }

  console.log(
    `   ✅ Operational Departure Slots Processed: ${CANONICAL_DEPARTURE_SLOTS.length}/86 slots (${totalCreated} created, ${totalUpdated} updated across 7 fixed-date packages).`,
  )

  return {
    totalProcessed: CANONICAL_DEPARTURE_SLOTS.length,
    totalCreated,
    totalUpdated,
    slotsByExperience,
  }
}
