import dotenv from 'dotenv'
import path from 'path'
dotenv.config({ path: path.resolve(process.cwd(), '.env') })
process.env.VITEST = 'true'

async function run() {
  console.log('================================================================================')
  console.log('🧪 ACCOMMODATION ADMIN PERSISTENCE TEST MATRIX')
  console.log('================================================================================\n')

  // 1. Authenticate via REST API
  const loginRes = await fetch('http://localhost:3000/api/users/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: 'admin@laubevoyage.com', password: 'Admin@123' }),
  })
  const loginData = await loginRes.json()
  const authHeader = 'JWT ' + loginData.token
  console.log('✅ Authenticated as Admin via REST API:', loginData.user?.email)

  // 2. Fetch Package #1955
  const getExp = async () => {
    const res = await fetch('http://localhost:3000/api/experiences/1955?depth=0', {
      headers: { Authorization: authHeader },
    })
    return await res.json()
  }

  const patchExp = async (data: any) => {
    const res = await fetch('http://localhost:3000/api/experiences/1955?depth=0', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: authHeader,
      },
      body: JSON.stringify(data),
    })
    const json = await res.json()
    return { status: res.status, data: json }
  }

  const initialDoc = await getExp()
  console.log(`[Reconnaissance] Package #1955 Stays Count: ${initialDoc.accommodations?.length}`)
  const originalBackup = JSON.parse(JSON.stringify(initialDoc.accommodations))

  try {
    // TEST MATRIX A: Edit existing option & room rate
    console.log('\n--- MATRIX A: Edit Existing Option & Room Rate ---')
    const updatedStaysA = JSON.parse(JSON.stringify(initialDoc.accommodations))
    updatedStaysA[0].nights = 6
    updatedStaysA[0].options[0].roomCategory = 'Royal Penthouse Suite'
    updatedStaysA[0].options[0].roomRates[0].rateEGP = 15500

    const patchA = await patchExp({ accommodations: updatedStaysA })
    if (patchA.status !== 200) {
      throw new Error(`Matrix A PATCH failed (${patchA.status}): ${JSON.stringify(patchA.data)}`)
    }
    console.log('✅ Matrix A PATCH returned HTTP 200 OK.')

    const verifiedDocA = await getExp()
    if (
      verifiedDocA.accommodations[0].nights !== 6 ||
      verifiedDocA.accommodations[0].options[0].roomCategory !== 'Royal Penthouse Suite' ||
      Number(verifiedDocA.accommodations[0].options[0].roomRates[0].rateEGP) !== 15500
    ) {
      throw new Error('Matrix A persistence mismatch in database!')
    }
    console.log('✅ Matrix A Database verification: Nights=6, Category="Royal Penthouse Suite", Rate=15500 EGP.')

    // TEST MATRIX B: Add a new option to Stay 1
    console.log('\n--- MATRIX B: Add New Option to Stay 1 ---')
    const updatedStaysB = JSON.parse(JSON.stringify(verifiedDocA.accommodations))
    updatedStaysB[0].options.push({
      property: 15, // Armani Hotel Dubai
      roomCategory: 'Classic City View',
      boardBasis: 'half_board',
      pricingUnit: 'per_stay',
      roomRates: [
        { occupancy: 'single', rateEGP: 6500, enabled: true },
        { occupancy: 'double', rateEGP: 9000, enabled: true },
      ],
    })

    const patchB = await patchExp({ accommodations: updatedStaysB })
    if (patchB.status !== 200) {
      throw new Error(`Matrix B PATCH failed (${patchB.status}): ${JSON.stringify(patchB.data)}`)
    }
    console.log('✅ Matrix B PATCH returned HTTP 200 OK.')

    const verifiedDocB = await getExp()
    if (verifiedDocB.accommodations[0].options.length !== 2) {
      throw new Error(`Matrix B options count mismatch: expected 2, got ${verifiedDocB.accommodations[0].options.length}`)
    }
    const newOption = verifiedDocB.accommodations[0].options[1]
    if (!newOption.id || typeof newOption.id !== 'string') {
      throw new Error(`Matrix B option ID not generated by Payload! ID: ${newOption.id}`)
    }
    console.log(`✅ Matrix B Database verification: 2 options in Stay 1, new option ID: "${newOption.id}".`)

    // TEST MATRIX C: Delete an option from Stay 1
    console.log('\n--- MATRIX C: Delete an Option from Stay 1 ---')
    const updatedStaysC = JSON.parse(JSON.stringify(verifiedDocB.accommodations))
    updatedStaysC[0].options = updatedStaysC[0].options.filter((_: any, idx: number) => idx !== 1)

    const patchC = await patchExp({ accommodations: updatedStaysC })
    if (patchC.status !== 200) {
      throw new Error(`Matrix C PATCH failed (${patchC.status}): ${JSON.stringify(patchC.data)}`)
    }
    console.log('✅ Matrix C PATCH returned HTTP 200 OK.')

    const verifiedDocC = await getExp()
    if (verifiedDocC.accommodations[0].options.length !== 1) {
      throw new Error(`Matrix C options count mismatch: expected 1, got ${verifiedDocC.accommodations[0].options.length}`)
    }
    console.log('✅ Matrix C Database verification: Option successfully deleted, exactly 1 option remains in Stay 1.')

    // TEST MATRIX D: Multi-Option 2x2 Structure Persistence
    console.log('\n--- MATRIX D: Multi-Option 2x2 (Stay 1 has 2 opts, Stay 2 has 2 opts) ---')
    const updatedStaysD = [
      {
        order: 1,
        nights: 4,
        options: [
          {
            property: 17,
            roomCategory: 'Grand Deluxe Room',
            boardBasis: 'bed_and_breakfast',
            pricingUnit: 'per_stay',
            roomRates: [
              { occupancy: 'single', rateEGP: 6000, enabled: true },
              { occupancy: 'double', rateEGP: 9500, enabled: true },
            ],
          },
          {
            property: 16,
            roomCategory: 'Opera Suite',
            boardBasis: 'half_board',
            pricingUnit: 'per_night',
            roomRates: [
              { occupancy: 'single', rateEGP: 8000, enabled: true },
              { occupancy: 'double', rateEGP: 13000, enabled: true },
            ],
          },
        ],
      },
      {
        order: 2,
        nights: 3,
        options: [
          {
            property: 15,
            roomCategory: 'Armani Suite',
            boardBasis: 'all_inclusive',
            pricingUnit: 'per_stay',
            roomRates: [
              { occupancy: 'single', rateEGP: 7000, enabled: true },
              { occupancy: 'double', rateEGP: 11000, enabled: true },
            ],
          },
          {
            property: 14,
            roomCategory: 'Desert Villa',
            boardBasis: 'full_board',
            pricingUnit: 'per_night',
            roomRates: [
              { occupancy: 'single', rateEGP: 12000, enabled: true },
              { occupancy: 'double', rateEGP: 18000, enabled: true },
            ],
          },
        ],
      },
    ]

    const patchD = await patchExp({ accommodations: updatedStaysD })
    if (patchD.status !== 200) {
      throw new Error(`Matrix D PATCH failed (${patchD.status}): ${JSON.stringify(patchD.data)}`)
    }
    console.log('✅ Matrix D PATCH returned HTTP 200 OK.')

    const verifiedDocD = await getExp()
    if (
      verifiedDocD.accommodations.length !== 2 ||
      verifiedDocD.accommodations[0].options.length !== 2 ||
      verifiedDocD.accommodations[1].options.length !== 2
    ) {
      throw new Error('Matrix D 2x2 structure mismatch in database!')
    }
    console.log('✅ Matrix D Database verification: Exact 2x2 Stays and Options persisted cleanly with valid IDs.')

    console.log('\n🎉 ALL ADMIN TEST MATRIX PHASES COMPLETED WITH 100% SUCCESS!')
  } finally {
    // Restore initial accommodations
    console.log('\nRestoring Package #1955 original state...')
    await patchExp({ accommodations: originalBackup })
    console.log('✅ Original accommodations restored.')
  }

  process.exit(0)
}

run().catch((err) => {
  console.error('\n❌ TEST MATRIX FAILED:', err)
  process.exit(1)
})
