import type { CollectionPresentationConfig } from '../types'

/**
 * Presentation-Only Metadata for Experiences Collection.
 * Does NOT own the columns or the defaults (Payload useTableColumns owns them).
 * Dictates only HOW a field is visually rendered when active in Payload.
 */
export const experiencesPresentation: CollectionPresentationConfig = {
  collectionSlug: 'experiences',
  title: 'Experiences',
  description: 'Curate bespoke travel itineraries, departures and tour packages',
  overrides: {
    hero: {
      header: 'Image',
      width: 72,
      minWidth: 72,
      maxWidth: 72,
      resizable: false,
      sortable: false,
      cellType: 'thumbnail',
    },
    thumbnail: {
      header: 'Image',
      width: 72,
      minWidth: 72,
      maxWidth: 72,
      resizable: false,
      sortable: false,
      cellType: 'thumbnail',
    },
    title: {
      header: 'Title',
      width: 280,
      minWidth: 220,
      resizable: true,
      sortable: true,
      cellType: 'title',
    },
    city: {
      header: 'City',
      width: 140,
      minWidth: 100,
      resizable: true,
      sortable: false,
      cellType: 'location',
    },
    type: {
      header: 'Type',
      width: 125,
      minWidth: 100,
      resizable: true,
      sortable: true,
      cellType: 'badge',
    },
    price: {
      header: 'Price',
      width: 145,
      minWidth: 120,
      resizable: true,
      sortable: true,
      cellType: 'price',
    },
    availability: {
      header: 'Availability',
      width: 135,
      minWidth: 110,
      resizable: true,
      sortable: true,
      cellType: 'badge',
    },
    updatedAt: {
      header: 'Updated At',
      width: 145,
      minWidth: 120,
      resizable: true,
      sortable: true,
      cellType: 'date',
    },
    createdAt: {
      header: 'Created At',
      width: 145,
      minWidth: 120,
      resizable: true,
      sortable: true,
      cellType: 'date',
    },
    id: {
      header: 'ID',
      width: 160,
      minWidth: 120,
      resizable: true,
      sortable: false,
      cellType: 'text',
    },
    slug: {
      header: 'Slug',
      width: 180,
      minWidth: 140,
      resizable: true,
      sortable: true,
      cellType: 'text',
    },
    packageMode: {
      header: 'Package Mode',
      width: 140,
      minWidth: 120,
      resizable: true,
      sortable: true,
      cellType: 'badge',
    },
    'duration.days': {
      header: 'Days',
      width: 100,
      minWidth: 80,
      resizable: true,
      sortable: true,
      cellType: 'text',
    },
    'duration.nights': {
      header: 'Nights',
      width: 100,
      minWidth: 80,
      resizable: true,
      sortable: true,
      cellType: 'text',
    },
    accommodations: {
      header: 'Accommodations',
      width: 170,
      minWidth: 140,
      resizable: true,
      sortable: false,
      cellType: 'accommodations',
    },
    itinerary: {
      header: 'Itinerary',
      width: 120,
      minWidth: 100,
      resizable: true,
      sortable: false,
      cellType: 'itinerary',
    },
    gallery: {
      header: 'Gallery',
      width: 120,
      minWidth: 100,
      resizable: true,
      sortable: false,
      cellType: 'gallery',
    },
  },
  rowActions: [
    {
      id: 'edit',
      label: 'Edit Experience',
      hrefTemplate: '/admin/collections/experiences/{id}',
    },
    {
      id: 'preview',
      label: 'View on Site',
      hrefTemplate: '/experiences/{slug}',
    },
  ],
  capabilities: {
    selection: true,
    metrics: true,
  },
  toolbar: {
    searchPlaceholder: 'Search by title or slug...',
    quickFilters: [
      {
        id: 'city',
        field: 'city',
        label: 'Cities',
        placeholder: 'All Cities',
        source: {
          type: 'relationship',
          relationTo: 'cities',
          labelField: 'name',
          valueField: 'id',
        },
      },
      {
        id: 'type',
        field: 'type',
        label: 'Types',
        placeholder: 'All Types',
        source: {
          type: 'static',
          options: [
            { label: 'Package', value: 'package' },
            { label: 'Daily Tour', value: 'daily_tour' },
          ],
        },
      },
      {
        id: 'availability',
        field: 'availability',
        label: 'Availability',
        placeholder: 'All Availability',
        source: {
          type: 'static',
          options: [
            { label: 'Available', value: 'available' },
            { label: 'Sold Out', value: 'sold_out' },
            { label: 'Coming Soon', value: 'coming_soon' },
            { label: 'Unavailable', value: 'unavailable' },
          ],
        },
      },
    ],
    capabilities: {
      search: true,
      quickFilters: true,
      columns: true,
      advancedFilters: true,
      reset: true,
    },
  },
}
