/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ManagementMember".
 */
export type ManagementMember =
  | {
      name: string;
      position: string;
      bio?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      image?: (number | null) | Media;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    packages: Package;
    bookings: Booking;
    'blog-posts': BlogPost;
    excursions: Excursion;
    'loyalty-points': LoyaltyPoint;
    emails: Email;
    destinations: Destination;
    hotels: Hotel;
    'contact-inquiries': ContactInquiry;
    reviews: Review;
    cities: City;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    excursions: ExcursionsSelect<false> | ExcursionsSelect<true>;
    'loyalty-points': LoyaltyPointsSelect<false> | LoyaltyPointsSelect<true>;
    emails: EmailsSelect<false> | EmailsSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'company-settings': CompanySetting;
    'home-page': HomePage;
    'about-page-config': AboutPageConfig;
    'loyalty-settings': LoyaltySetting;
  };
  globalsSelect: {
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page-config': AboutPageConfigSelect<false> | AboutPageConfigSelect<true>;
    'loyalty-settings': LoyaltySettingsSelect<false> | LoyaltySettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'customer';
  name: string;
  isVerified?: boolean | null;
  verificationCode?: string | null;
  loyaltyTier?: ('traveler' | 'explorer' | 'voyager') | null;
  loyaltyPoints?: number | null;
  /**
   * Total cumulative spend for tier calculation
   */
  totalSpend?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  _order?: string | null;
  title: string;
  relatedDestination?: (number | null) | Destination;
  /**
   * Select or create a city
   */
  city?: (number | City)[] | null;
  slug?: string | null;
  /**
   * Select hotels associated with this package
   */
  hotels?: (number | Hotel)[] | null;
  adultPrice: number;
  infantPrice: number;
  price?: number | null;
  dates?:
    | {
        startDate?: string | null;
        endDate?: string | null;
        /**
         * Leave empty to use the package default price
         */
        adultPrice?: number | null;
        /**
         * Leave empty to use the package default price
         */
        infantPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  itinerary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Automatically generated from description if left blank
   */
  excerpt?: string | null;
  /**
   * Detail transfers, meals, insurance, etc.
   */
  whatsIncluded?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  duration?: string | null;
  tourType?: string | null;
  groupSize?: string | null;
  languages?: string | null;
  heroImage: number | Media;
  /**
   * Select multiple images for the package gallery (Bulk selection supported)
   */
  gallery?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug?: string | null;
  region: 'europe' | 'middle-east' | 'africa' | 'asia' | 'americas' | 'local';
  country: string;
  image: number | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: number;
  name: string;
  location: string;
  stars: number;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  amenities?: ('pool' | 'spa' | 'gym' | 'wifi' | 'restaurant' | 'all-inclusive')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  user: number | User;
  package: number | Package;
  /**
   * Preferred email for booking communications
   */
  contactEmail: string;
  contactPhone: string;
  bookingDate: string;
  travelersList: {
    fullName: string;
    type: 'adult' | 'infant';
    passportNumber?: string | null;
    specialRequests?: string | null;
    id?: string | null;
  }[];
  /**
   * Add-on experiences selected for this booking
   */
  selectedExcursions?: (number | Excursion)[] | null;
  /**
   * Number of loyalty points used to discount this booking
   */
  pointsRedeemed?: number | null;
  /**
   * The monetary value deducted from the subtotal using points
   */
  discountAmount?: number | null;
  totalPrice: number;
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  notes?: string | null;
  receipt?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "excursions".
 */
export interface Excursion {
  id: number;
  _order?: string | null;
  title: string;
  slug?: string | null;
  relatedDestination?: (number | null) | Destination;
  /**
   * Cities where this excursion is available (used for smart cross-selling)
   */
  city?: (number | City)[] | null;
  price: number;
  duration?: string | null;
  tourType?: string | null;
  groupSize?: string | null;
  languages?: string | null;
  category: 'sea-trips' | 'safari-adventure' | 'cultural-history' | 'family-kids';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Write the itinerary schedule. Use headings for times and paragraphs for activities.
   */
  itinerary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whatsIncluded?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  whatToBring?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mainImage?: (number | null) | Media;
  /**
   * Select multiple images for the package gallery (Bulk selection supported)
   */
  gallery?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary shown on blog listing
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  categories?: ('travel-tips' | 'destinations' | 'culture' | 'food-dining' | 'adventure' | 'luxury')[] | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-points".
 */
export interface LoyaltyPoint {
  id: number;
  user: number | User;
  points: number;
  type: 'earned' | 'redeemed' | 'admin';
  reason: string;
  booking?: (number | null) | Booking;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emails".
 */
export interface Email {
  id: number;
  subject: string;
  to: string;
  type: 'welcome' | 'verification' | 'booking_confirmation' | 'tier_jump' | 'points_earned' | 'reset_password';
  status?: ('sent' | 'failed' | 'pending') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  user: number | User;
  /**
   * Template variables and debugging data
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: 'booking' | 'reservation' | 'loyalty' | 'feedback' | 'partnership';
  /**
   * Optional - for booking inquiries
   */
  preferredTravelDate?: string | null;
  destination?: string | null;
  /**
   * Minimum 50 characters
   */
  message: string;
  status?: ('new' | 'in-progress' | 'responded' | 'closed') | null;
  /**
   * Internal use only
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  user: number | User;
  excursion: number | Excursion;
  /**
   * 1-5 star rating
   */
  rating: number;
  title: string;
  comment: string;
  /**
   * When did you take this excursion?
   */
  tripDate?: string | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  /**
   * Official response from L'Aube Voyage
   */
  adminResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'excursions';
        value: number | Excursion;
      } | null)
    | ({
        relationTo: 'loyalty-points';
        value: number | LoyaltyPoint;
      } | null)
    | ({
        relationTo: 'emails';
        value: number | Email;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'hotels';
        value: number | Hotel;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  isVerified?: T;
  verificationCode?: T;
  loyaltyTier?: T;
  loyaltyPoints?: T;
  totalSpend?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  relatedDestination?: T;
  city?: T;
  slug?: T;
  hotels?: T;
  adultPrice?: T;
  infantPrice?: T;
  price?: T;
  dates?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        adultPrice?: T;
        infantPrice?: T;
        id?: T;
      };
  description?: T;
  itinerary?: T;
  excerpt?: T;
  whatsIncluded?: T;
  duration?: T;
  tourType?: T;
  groupSize?: T;
  languages?: T;
  heroImage?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  user?: T;
  package?: T;
  contactEmail?: T;
  contactPhone?: T;
  bookingDate?: T;
  travelersList?:
    | T
    | {
        fullName?: T;
        type?: T;
        passportNumber?: T;
        specialRequests?: T;
        id?: T;
      };
  selectedExcursions?: T;
  pointsRedeemed?: T;
  discountAmount?: T;
  totalPrice?: T;
  status?: T;
  notes?: T;
  receipt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  categories?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "excursions_select".
 */
export interface ExcursionsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  relatedDestination?: T;
  city?: T;
  price?: T;
  duration?: T;
  tourType?: T;
  groupSize?: T;
  languages?: T;
  category?: T;
  description?: T;
  itinerary?: T;
  whatsIncluded?: T;
  whatToBring?: T;
  mainImage?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-points_select".
 */
export interface LoyaltyPointsSelect<T extends boolean = true> {
  user?: T;
  points?: T;
  type?: T;
  reason?: T;
  booking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emails_select".
 */
export interface EmailsSelect<T extends boolean = true> {
  subject?: T;
  to?: T;
  type?: T;
  status?: T;
  content?: T;
  user?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  region?: T;
  country?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  stars?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  amenities?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  preferredTravelDate?: T;
  destination?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  excursion?: T;
  rating?: T;
  title?: T;
  comment?: T;
  tripDate?: T;
  status?: T;
  adminResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage core company details, branding, contact info, and social links across the platform.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  /**
   * This name appears in emails, footprints, and headers.
   */
  companyName: string;
  /**
   * A short catchy phrase (e.g., "Your ultimate travel partner").
   */
  slogan?: string | null;
  /**
   * Upload the primary brand logo (SVG or clear PNG recommended).
   */
  logo?: (number | null) | Media;
  /**
   * A brief 1-2 sentence description about the company for the website footer.
   */
  footerAboutText?: string | null;
  email: string;
  phone: string;
  whatsapp?: string | null;
  /**
   * The physical address displayed on the website contact page.
   */
  address?: string | null;
  googleMapsLink?: string | null;
  workingHours?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  x?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  /**
   * Optional business registration number.
   */
  commercialRegistration?: string | null;
  /**
   * Optional tax identification number.
   */
  taxId?: string | null;
  /**
   * SMTP host (e.g. mail.laubevoyage.com)
   */
  smtpHost: string;
  /**
   * SMTP port (e.g. 465 or 587)
   */
  smtpPort: number;
  /**
   * Checked for port 465, unchecked for 587
   */
  smtpSecure?: boolean | null;
  contactMail: {
    email: string;
    password: string;
  };
  reservationMail: {
    email: string;
    password: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    title: string;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  /**
   * Select destinations to highlight in the homepage carousel
   */
  featuredDestinations?: (number | Destination)[] | null;
  /**
   * YouTube videos for the homepage video gallery section
   */
  videoGallery?:
    | {
        title: string;
        /**
         * Full YouTube URL or embed URL
         */
        youtubeUrl: string;
        description?: string | null;
        category?: ('lifestyle' | 'testimonial' | 'event' | 'bts') | null;
        /**
         * Custom thumbnail (optional, uses YouTube default if empty)
         */
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-config".
 */
export interface AboutPageConfig {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    image: number | Media;
  };
  history: {
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image?: (number | null) | Media;
  };
  philosophy: {
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Enter one characteristic per line (e.g. Integrity, Excellence, Innovation)
     */
    characteristics?: string | null;
  };
  missionVision?: {
    /**
     * Mission: Through Travel, we connect people to new experiences in a safe and secured environment hiring the best calibers in Tourism to serve our customers in an optimum manner
     */
    mission?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Vision: To create a community where everyone in able to travel
     */
    vision?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  management?: ManagementMember;
  accreditations?:
    | {
        title: string;
        organization?: string | null;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  specializedPrograms?: {
    cultural?: {
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      image?: (number | null) | Media;
    };
    incentive?: {
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      image?: (number | null) | Media;
    };
    adventure?: {
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      image?: (number | null) | Media;
    };
  };
  transport?: {
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure loyalty points earning rates, redemption tiers, and membership levels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-settings".
 */
export interface LoyaltySetting {
  id: number;
  /**
   * How customers earn points from bookings.
   */
  earning: {
    /**
     * Points earned per $1 spent. Example: 0.1 = 1 point per $10 spent.
     */
    pointsPerDollar: number;
    /**
     * Explorer tier bonus multiplier (e.g., 1.2 = 20% bonus points).
     */
    explorerMultiplier: number;
    /**
     * Voyager tier bonus multiplier (e.g., 1.5 = 50% bonus points).
     */
    voyagerMultiplier: number;
  };
  /**
   * How much total spend is needed to reach each tier.
   */
  tiers: {
    /**
     * Minimum total spend ($) for Explorer tier.
     */
    explorerThreshold: number;
    /**
     * Minimum total spend ($) for Voyager tier.
     */
    voyagerThreshold: number;
  };
  /**
   * Define how many points customers can redeem and what discount they receive. These appear at checkout and in the dashboard.
   */
  redemptionTiers: {
    /**
     * Number of points to redeem.
     */
    points: number;
    /**
     * Discount value ($) given for these points.
     */
    discountValue: number;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  companyName?: T;
  slogan?: T;
  logo?: T;
  footerAboutText?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  googleMapsLink?: T;
  workingHours?: T;
  instagram?: T;
  facebook?: T;
  x?: T;
  linkedin?: T;
  youtube?: T;
  tiktok?: T;
  commercialRegistration?: T;
  taxId?: T;
  smtpHost?: T;
  smtpPort?: T;
  smtpSecure?: T;
  contactMail?:
    | T
    | {
        email?: T;
        password?: T;
      };
  reservationMail?:
    | T
    | {
        email?: T;
        password?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  featuredDestinations?: T;
  videoGallery?:
    | T
    | {
        title?: T;
        youtubeUrl?: T;
        description?: T;
        category?: T;
        thumbnail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-config_select".
 */
export interface AboutPageConfigSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  history?:
    | T
    | {
        content?: T;
        image?: T;
      };
  philosophy?:
    | T
    | {
        content?: T;
        characteristics?: T;
      };
  missionVision?:
    | T
    | {
        mission?: T;
        vision?: T;
      };
  management?: T | ManagementMemberSelect<T>;
  accreditations?:
    | T
    | {
        title?: T;
        organization?: T;
        logo?: T;
        id?: T;
      };
  specializedPrograms?:
    | T
    | {
        cultural?:
          | T
          | {
              description?: T;
              image?: T;
            };
        incentive?:
          | T
          | {
              description?: T;
              image?: T;
            };
        adventure?:
          | T
          | {
              description?: T;
              image?: T;
            };
      };
  transport?:
    | T
    | {
        content?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ManagementMember_select".
 */
export interface ManagementMemberSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  bio?: T;
  image?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-settings_select".
 */
export interface LoyaltySettingsSelect<T extends boolean = true> {
  earning?:
    | T
    | {
        pointsPerDollar?: T;
        explorerMultiplier?: T;
        voyagerMultiplier?: T;
      };
  tiers?:
    | T
    | {
        explorerThreshold?: T;
        voyagerThreshold?: T;
      };
  redemptionTiers?:
    | T
    | {
        points?: T;
        discountValue?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}