/* THIS FILE IS 100% GENERATED BY THE PAYLOAD CLI */
import { RootLayout, handleServerFunctions } from '@payloadcms/next/layouts'
import { importMap } from './admin/importMap'
import config from '@/payload.config'

import '@payloadcms/next/css'
import '@/styles/payloadStyles.css'
import './admin/styles/admin-theme.scss'

type Args = {
  children: React.ReactNode
}

const serverFunction: React.ComponentProps<typeof RootLayout>['serverFunction'] = async (args) => {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

const Layout = ({ children }: Args) => (
  <RootLayout
    config={config}
    htmlProps={{ suppressHydrationWarning: true }}
    importMap={importMap}
    serverFunction={serverFunction}
  >
    {children}
  </RootLayout>
)

export default Layout
