/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    countries: Country;
    cities: City;
    accommodations: Accommodation;
    experiences: Experience;
    bookings: Booking;
    'point-ledger': PointLedger;
    'exchange-rates': ExchangeRate;
    currencies: Currency;
    'translation-cache': TranslationCache;
    'admin-audit-logs': AdminAuditLog;
    'customer-notification-preferences': CustomerNotificationPreference;
    'customer-travelers': CustomerTraveler;
    'dashboard-projections': DashboardProjection;
    faqs: Faq;
    'maintenance-logs': MaintenanceLog;
    'media-gallery': MediaGallery;
    'notification-logs': NotificationLog;
    pages: Page;
    'payment-transactions': PaymentTransaction;
    posts: Post;
    redirects: Redirect;
    reviews: Review;
    coupons: Coupon;
    'contact-requests': ContactRequest;
    languages: Language;
    'departure-slots': DepartureSlot;
    'event-outbox': EventOutbox;
    'event-inbox': EventInbox;
    'maintenance-leases': MaintenanceLease;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    accommodations: AccommodationsSelect<false> | AccommodationsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'point-ledger': PointLedgerSelect<false> | PointLedgerSelect<true>;
    'exchange-rates': ExchangeRatesSelect<false> | ExchangeRatesSelect<true>;
    currencies: CurrenciesSelect<false> | CurrenciesSelect<true>;
    'translation-cache': TranslationCacheSelect<false> | TranslationCacheSelect<true>;
    'admin-audit-logs': AdminAuditLogsSelect<false> | AdminAuditLogsSelect<true>;
    'customer-notification-preferences': CustomerNotificationPreferencesSelect<false> | CustomerNotificationPreferencesSelect<true>;
    'customer-travelers': CustomerTravelersSelect<false> | CustomerTravelersSelect<true>;
    'dashboard-projections': DashboardProjectionsSelect<false> | DashboardProjectionsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'maintenance-logs': MaintenanceLogsSelect<false> | MaintenanceLogsSelect<true>;
    'media-gallery': MediaGallerySelect<false> | MediaGallerySelect<true>;
    'notification-logs': NotificationLogsSelect<false> | NotificationLogsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payment-transactions': PaymentTransactionsSelect<false> | PaymentTransactionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'contact-requests': ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    'departure-slots': DepartureSlotsSelect<false> | DepartureSlotsSelect<true>;
    'event-outbox': EventOutboxSelect<false> | EventOutboxSelect<true>;
    'event-inbox': EventInboxSelect<false> | EventInboxSelect<true>;
    'maintenance-leases': MaintenanceLeasesSelect<false> | MaintenanceLeasesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'system-settings': SystemSetting;
    'loyalty-settings': LoyaltySetting;
  };
  globalsSelect: {
    'system-settings': SystemSettingsSelect<false> | SystemSettingsSelect<true>;
    'loyalty-settings': LoyaltySettingsSelect<false> | LoyaltySettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'super_admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  passportNumber?: string | null;
  nationality?: string | null;
  status: 'active' | 'inactive' | 'suspended' | 'pending_verification' | 'pending_deletion' | 'deleted';
  failedLoginAttempts?: number | null;
  lockedUntil?: string | null;
  lastLoginAt?: string | null;
  emailVerifiedAt?: string | null;
  verificationExpiresAt?: string | null;
  phoneVerifiedAt?: string | null;
  deletedAt?: string | null;
  loyalty?: {
    /**
     * Tier is managed dynamically by LoyaltyService
     */
    tier?: string | null;
    /**
     * Cached value - source of truth is PointLedger
     */
    points?: number | null;
    /**
     * Total spent in EGP - used for tier calculation
     */
    totalSpent?: number | null;
    tierAchievedAt?: string | null;
  };
  preferences?: {
    /**
     * E.g., en-US, ar-EG. Controls dates, numbers, and separators.
     */
    preferredLocale?: string | null;
    preferredLanguage?: string | null;
    /**
     * Must match an active ISO Code in Currencies catalog
     */
    preferredCurrency?: string | null;
    preferredTimezone?: string | null;
    measurementSystem?: ('metric' | 'imperial') | null;
    notifications?: {
      email?: boolean | null;
      sms?: boolean | null;
      push?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  slug: string;
  /**
   * ISO 3166-1 alpha-2 country code
   */
  code: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Official national display currency for this country (SSOT)
   */
  currency?: (number | null) | Currency;
  /**
   * Official default language for this country used for default UI rendering
   */
  defaultLanguage?: (number | null) | Language;
  /**
   * Primary IANA Timezone (e.g. Europe/Berlin, Africa/Cairo)
   */
  timezone?: string | null;
  measurementSystem?: ('metric' | 'imperial') | null;
  /**
   * First day of the week (0 = Sunday, 1 = Monday, 6 = Saturday)
   */
  weekStart?: number | null;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Master Catalog of Currencies (Identity only, no live rates)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies".
 */
export interface Currency {
  id: number;
  /**
   * ISO 4217 Currency Code (e.g., USD, EUR, JPY)
   */
  isoCode: string;
  /**
   * ISO 4217 Numeric Code (e.g., 840 for USD)
   */
  numericCode: number;
  /**
   * Full name (e.g., US Dollar)
   */
  name: string;
  /**
   * Common symbol (e.g., $)
   */
  symbol: string;
  /**
   * Native symbol (e.g., US$)
   */
  nativeSymbol?: string | null;
  /**
   * Number of decimal places (e.g., 2 for USD, 0 for JPY)
   */
  decimals: number;
  /**
   * Two-letter country code for flags (e.g., us, eu, eg, sa)
   */
  flagCode?: string | null;
  /**
   * Enable or disable this currency in the frontend
   */
  isActive?: boolean | null;
  displayOrder?: number | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Master catalog of active and supported website languages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  /**
   * Administrative language name (e.g. English, Arabic)
   */
  name: string;
  /**
   * Language name as shown in the UI switcher (e.g. English, العربية, Français)
   */
  nativeName: string;
  /**
   * ISO language code (e.g. en, ar, fr)
   */
  code: string;
  /**
   * Check if this language is read Right-to-Left (e.g. Arabic)
   */
  isRTL?: boolean | null;
  /**
   * Enable or disable this language site-wide
   */
  isActive?: boolean | null;
  /**
   * Set as the fallback language for the entire platform
   */
  isDefault?: boolean | null;
  /**
   * Order of appearance in the language switcher dropdown
   */
  displayOrder?: number | null;
  /**
   * The recommended display currency chosen for users browsing in this language (e.g. USD for English, EUR for German)
   */
  preferredDisplayCurrency?: (number | null) | Currency;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  slug: string;
  country: number | Country;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations".
 */
export interface Accommodation {
  id: number;
  /**
   * Physical establishment name (e.g. Four Seasons Hotel Cairo at Nile Plaza).
   */
  name: string;
  /**
   * Unique URL-safe identifier for this property.
   */
  slug: string;
  /**
   * Hospitality establishment classification.
   */
  type: 'hotel' | 'resort' | 'cruise' | 'lodge' | 'camp';
  /**
   * Authoritative geographical city location.
   */
  city: number | City;
  /**
   * Curated star classification (1 to 5).
   */
  rating?: number | null;
  /**
   * Primary showcase image of the property.
   */
  heroImage?: (number | null) | Media;
  /**
   * High-resolution photo gallery of rooms and amenities.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Curated property overview, highlights, and atmosphere.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  slug: string;
  type: 'package' | 'daily_tour';
  packageMode?: ('fixed_date' | 'flexible_date') | null;
  /**
   * Origin / Departure Gateway City (where the journey officially commences and initial meeting occurs).
   */
  city: number | City;
  /**
   * Ordered Post-Origin Destinations (all sequential cities visited AFTER departing from the Origin city). Do NOT re-add the Origin city.
   */
  destinations?: (number | City)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  duration?: {
    /**
     * Total tour duration in days for multi-day Packages (e.g. 5). Required for packages.
     */
    days?: number | null;
    /**
     * Total number of nights for multi-day Packages (e.g. 4). Optional.
     */
    nights?: number | null;
    /**
     * Tour duration for Daily Tours entered in Hours (e.g. 3 for 3 hours, 1.5 for 90 minutes) and stored deterministically as minutes. Required for daily_tour.
     */
    durationMinutes?: number | null;
  };
  /**
   * Base Journey Price per Adult in EGP — Excluding Accommodation (covers touring, private transport, expert guiding, and included provisions).
   */
  price?: number | null;
  availability: 'available' | 'sold_out' | 'coming_soon' | 'unavailable';
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  itinerary?:
    | {
        dayNumber: number;
        title: string;
        /**
         * Geographical city waypoint for this specific day (optional).
         */
        city?: (number | null) | City;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Curated accommodation stays included in this multi-day Package.
   */
  accommodations?:
    | {
        /**
         * Sequential order of this stay within the itinerary (1, 2, ...).
         */
        order: number;
        /**
         * Reusable Accommodation Property entity from catalog.
         */
        property: number | Accommodation;
        /**
         * Number of nights for this stay (must be >= 1).
         */
        nights: number;
        /**
         * Optional package-specific room category (e.g. Deluxe Nile View Room, Luxury Suite).
         */
        roomCategory?: string | null;
        boardBasis?: ('bed_and_breakfast' | 'half_board' | 'full_board' | 'all_inclusive') | null;
        /**
         * Commercial pricing calculation unit for room rates in this stay.
         */
        pricingUnit: 'per_stay' | 'per_night';
        /**
         * Explicit commercial room rates and availability flags per occupancy type for this stay.
         */
        roomRates: {
          occupancy: 'single' | 'double' | 'triple' | 'quad';
          /**
           * Commercial room price in EGP for this stay (or per night if pricingUnit is per_night). Set 0 only if complimentary/bundled.
           */
          rateEGP: number;
          /**
           * Enable to offer this occupancy type for booking. Uncheck to disable and prevent reservation.
           */
          enabled?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Commercial child and infant pricing configuration (controlled by Administration).
   */
  childPolicy?: {
    /**
     * Are children allowed on this package experience?
     */
    childrenAllowed?: boolean | null;
    /**
     * Price percentage for child (2-11 yrs) sharing parents bed (e.g. 50 = 50% of adult base price).
     */
    childSharingBedPercentage?: number | null;
    /**
     * Price percentage for child (2-11 yrs) requiring an extra rollaway bed (e.g. 75 = 75% of adult base price).
     */
    childExtraBedPercentage?: number | null;
  };
  policies?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  /**
   * Recurring departure schedules for Daily Tours.
   */
  schedules?:
    | {
        startTime: string;
        /**
         * Optional operational vehicle/boat capacity guide.
         */
        defaultCapacity?: number | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Blackout dates or specific time exceptions when the tour is unavailable.
   */
  blackouts?:
    | {
        date: string;
        /**
         * Leave blank to blackout the entire day, or specify a time (e.g. 09:00).
         */
        startTime?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Date-specific price overrides (e.g. Holiday or Peak Season Pricing).
   */
  priceOverrides?:
    | {
        date: string;
        /**
         * Leave blank to apply to all times on this date, or specify (e.g. 09:00).
         */
        startTime?: string | null;
        priceEGP: number;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  _slotsPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  bookingNumber: string;
  idempotencyKey?: string | null;
  user: number | Customer;
  experience: number | Experience;
  departureSlot?: (number | null) | DepartureSlot;
  /**
   * Status can only be changed through BookingService
   */
  status:
    | 'draft'
    | 'pending_payment'
    | 'pending_admin_review'
    | 'paid'
    | 'confirmed'
    | 'completed'
    | 'cancelled'
    | 'refunded'
    | 'expired'
    | 'payment_received_after_expiry';
  travelers: {
    firstName: string;
    lastName: string;
    email?: string | null;
    phone?: string | null;
    dateOfBirth?: string | null;
    passportNumber?: string | null;
    nationality?: string | null;
    type?: ('adult' | 'child' | 'infant') | null;
    id?: string | null;
  }[];
  /**
   * Calendar start date of the booking (Local destination date)
   */
  startDate: string;
  /**
   * Calendar end date of the booking (Identical to Start Date for Daily Tours)
   */
  endDate: string;
  /**
   * Frozen operational moment when trip execution is completed
   */
  completionAt?: string | null;
  /**
   * Authoritative IANA destination timezone for the booking (e.g. Africa/Cairo)
   */
  destinationTimezone?: string | null;
  /**
   * Authoritative financial deadline for payment completion (ISO timestamp)
   */
  paymentWindowExpiresAt: string;
  /**
   * Immutable financial record of the booking
   */
  pricingSnapshot: {
    version?: number | null;
    basePriceEGP: number;
    promotionDiscountEGP?: number | null;
    couponDiscountEGP?: number | null;
    loyaltyDiscountEGP?: number | null;
    subtotalEGP: number;
    taxes?: number | null;
    fees?: number | null;
    totalAmountEGP: number;
    displayCurrency: string;
    displayAmount: number;
    exchangeRate: number;
    exchangeProvider?: string | null;
    exchangeRateTimestamp?: string | null;
    roundingStrategy?: string | null;
    currencyDecimals?: number | null;
  };
  /**
   * Calculated by LoyaltyService
   */
  pointsEarned?: number | null;
  paymentId?: string | null;
  /**
   * Frozen pickup or meeting point location snapshot for this booking
   */
  pickupLocation?: {
    label?: string | null;
    address?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    source?: ('map' | 'search' | 'current_location' | 'fixed_meeting_point') | null;
    instructions?: string | null;
  };
  notes?: string | null;
  source?: ('website' | 'admin' | 'api' | 'partner' | 'affiliate') | null;
  version?: number | null;
  paymentStatus: 'unpaid' | 'partially_paid' | 'paid' | 'refunded' | 'partially_refunded' | 'written_off';
  amountPaid: number;
  outstandingBalance: number;
  /**
   * Active/Committed capacity hold entity
   */
  capacityHold?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Active/Committed loyalty point hold entity
   */
  pointHold?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Ledger of all payment attempts
   */
  paymentAttempts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Customer-facing lifecycle timeline
   */
  timeline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * System audit log entries
   */
  auditTrail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * References to generated documents (Invoice, Voucher, Receipt)
   */
  documents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional booking data
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departure-slots".
 */
export interface DepartureSlot {
  id: number;
  departureId: string;
  experience: number | Experience;
  date: string;
  startTime?: string | null;
  /**
   * Optional price override in EGP for this slot. Inherits Experience.price if left blank.
   */
  priceOverrideEGP?: number | null;
  capacityTotal: number;
  capacityReserved: number;
  capacitySold: number;
  capacityAvailable: number;
  version: number;
  status: 'available' | 'sold_out' | 'blacked_out' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable ledger of all loyalty point transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-ledger".
 */
export interface PointLedger {
  id: number;
  user: number | Customer;
  ledgerVersion: number;
  referenceType?: ('booking' | 'admin_ticket' | 'system_welcome' | 'expiration_scan') | null;
  referenceId?: string | null;
  type:
    | 'earn'
    | 'earned'
    | 'redeem'
    | 'redeemed'
    | 'refund'
    | 'refunded'
    | 'reverse'
    | 'reversed'
    | 'welcome_bonus'
    | 'tier_bonus'
    | 'manual_adjustment'
    | 'expiration'
    | 'expired';
  /**
   * Positive for earning/bonus, negative for spending/reversal
   */
  amount: number;
  /**
   * Authoritative running balance (server-derived by beforeChange hook)
   */
  balance: number;
  reason: string;
  booking?: (number | null) | Booking;
  /**
   * Expiration date for earned points
   */
  expiresAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Live Financial Data for Exchange Rates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates".
 */
export interface ExchangeRate {
  id: number;
  /**
   * Base currency ISO code (e.g. EGP)
   */
  fromCurrency: string;
  /**
   * Target currency ISO code (e.g. USD)
   */
  toCurrency: string;
  /**
   * Exchange rate from base currency
   */
  rate: number;
  source: 'OpenExchange' | 'ExchangeRate-API' | 'FawazAhmed-CDN' | 'Manual';
  /**
   * Actual timestamp the rate was fetched/changed
   */
  lastUpdate?: string | null;
  /**
   * Last time this rate was successfully synced
   */
  lastSuccess?: string | null;
  /**
   * Last time a sync was attempted (whether success or fail)
   */
  lastAttempt?: string | null;
  /**
   * Reason for the last sync failure (e.g. Timeout)
   */
  lastError?: string | null;
  syncStatus?: ('synced' | 'failed' | 'stale') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Persistent versioned cache for translated text segments with TTL
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-cache".
 */
export interface TranslationCache {
  id: number;
  /**
   * SHA-256 hash of the original English source text
   */
  originalHash: string;
  sourceText: string;
  /**
   * Target locale code (e.g. ar, fr)
   */
  language: string;
  translatedText: string;
  /**
   * Translation engine used (e.g. google, libre, deepl)
   */
  provider: string;
  /**
   * Source document version at the time of translation
   */
  version: number;
  /**
   * Last time this translation was verified against the source version/hash
   */
  lastVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-audit-logs".
 */
export interface AdminAuditLog {
  id: number;
  auditId: string;
  adminUser: number | User;
  adminEmail: string;
  action: string;
  targetDomain: 'booking' | 'payment' | 'loyalty' | 'experience' | 'customer' | 'maintenance';
  targetId: string;
  reason: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  executedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-notification-preferences".
 */
export interface CustomerNotificationPreference {
  id: number;
  customer: number | Customer;
  marketingEmail?: boolean | null;
  marketingSMS?: boolean | null;
  marketingPush?: boolean | null;
  bookingEmail?: boolean | null;
  bookingSMS?: boolean | null;
  bookingPush?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-travelers".
 */
export interface CustomerTraveler {
  id: number;
  customer: number | Customer;
  firstName: string;
  lastName: string;
  dateOfBirth?: string | null;
  passportNumber?: string | null;
  relationship: 'spouse' | 'child' | 'parent' | 'friend' | 'other';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-projections".
 */
export interface DashboardProjection {
  id: number;
  projectionId: string;
  customer: number | Customer;
  projectionJson:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  faqId: string;
  category: 'booking' | 'cancellation' | 'payment' | 'loyalty';
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-logs".
 */
export interface MaintenanceLog {
  id: number;
  executionId: string;
  correlationId: string;
  jobName: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  startedBy: 'scheduler' | 'manual_admin' | 'api';
  status: 'running' | 'success' | 'failed' | 'partial_success';
  itemsProcessed?: number | null;
  itemsFailed?: number | null;
  durationMs?: number | null;
  jobVersion?: string | null;
  engineVersion?: string | null;
  errorDetails?: string | null;
  executedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery".
 */
export interface MediaGallery {
  id: number;
  mediaId: string;
  altText: string;
  fileUrl: string;
  mimeType: string;
  format?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-logs".
 */
export interface NotificationLog {
  id: number;
  notificationId: string;
  referenceType: string;
  referenceId: string;
  customer?: (number | null) | Customer;
  recipient: string;
  channel: 'email' | 'sms' | 'push' | 'whatsapp';
  category: 'marketing' | 'booking' | 'payment' | 'loyalty' | 'security';
  priority: 'critical' | 'high' | 'normal' | 'low';
  templateId: string;
  templateData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'queued' | 'processing' | 'sent' | 'delivered' | 'failed' | 'dlq';
  attempts?: number | null;
  lastError?: string | null;
  sentAt?: string | null;
  nextAttemptAt?: string | null;
  lastAttemptAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  pageId: string;
  slug: string;
  title: string;
  status: 'draft' | 'published';
  blocksJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-transactions".
 */
export interface PaymentTransaction {
  id: number;
  transactionId: string;
  bookingId: number;
  customerId: number;
  version?: number | null;
  provider: 'stripe' | 'bnpl' | 'manual';
  status: 'initiated' | 'processing' | 'successful' | 'failed' | 'refunded' | 'partially_refunded';
  /**
   * Gateway checkout session details
   */
  session?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Immutable ledger of gateway payment attempts
   */
  attempts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Database-first record of processed webhook event IDs
   */
  webhookLedger?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Payment security audit log entries
   */
  auditTrail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  gatewayReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  postId: string;
  slug: string;
  title: string;
  excerpt?: string | null;
  bodyHtml?: string | null;
  category?: string | null;
  authorName?: string | null;
  readTimeMinutes?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  redirectId: string;
  oldSlug: string;
  newSlug: string;
  statusCode: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewId: string;
  experience: number | Experience;
  customer: number | Customer;
  booking: number | Booking;
  rating: number;
  comment: string;
  status: 'pending_approval' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  couponId: string;
  code: string;
  discountType: 'percentage' | 'fixed_egp';
  discountValue: number;
  maxDiscountEGP?: number | null;
  minSpendEGP?: number | null;
  usageLimit?: number | null;
  usageCount?: number | null;
  status: 'active' | 'inactive' | 'expired';
  validFrom?: string | null;
  validUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests".
 */
export interface ContactRequest {
  id: number;
  name: string;
  email: string;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-outbox".
 */
export interface EventOutbox {
  id: number;
  eventId: string;
  correlationId: string;
  causationId?: string | null;
  eventType: string;
  eventVersion: number;
  aggregateType: string;
  aggregateId: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'published' | 'failed' | 'dead_letter';
  retryCount: number;
  nextRetryAt?: string | null;
  errorMessage?: string | null;
  publishedAt?: string | null;
  occurredAt: string;
  workerId?: string | null;
  lockExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-inbox".
 */
export interface EventInbox {
  id: number;
  idempotencyKey: string;
  processedEventId: string;
  subscriberName: string;
  processedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-leases".
 */
export interface MaintenanceLease {
  id: number;
  jobName: string;
  workerId: string;
  leaseExpiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'accommodations';
        value: number | Accommodation;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'point-ledger';
        value: number | PointLedger;
      } | null)
    | ({
        relationTo: 'exchange-rates';
        value: number | ExchangeRate;
      } | null)
    | ({
        relationTo: 'currencies';
        value: number | Currency;
      } | null)
    | ({
        relationTo: 'translation-cache';
        value: number | TranslationCache;
      } | null)
    | ({
        relationTo: 'admin-audit-logs';
        value: number | AdminAuditLog;
      } | null)
    | ({
        relationTo: 'customer-notification-preferences';
        value: number | CustomerNotificationPreference;
      } | null)
    | ({
        relationTo: 'customer-travelers';
        value: number | CustomerTraveler;
      } | null)
    | ({
        relationTo: 'dashboard-projections';
        value: number | DashboardProjection;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'maintenance-logs';
        value: number | MaintenanceLog;
      } | null)
    | ({
        relationTo: 'media-gallery';
        value: number | MediaGallery;
      } | null)
    | ({
        relationTo: 'notification-logs';
        value: number | NotificationLog;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'payment-transactions';
        value: number | PaymentTransaction;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'contact-requests';
        value: number | ContactRequest;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null)
    | ({
        relationTo: 'departure-slots';
        value: number | DepartureSlot;
      } | null)
    | ({
        relationTo: 'event-outbox';
        value: number | EventOutbox;
      } | null)
    | ({
        relationTo: 'event-inbox';
        value: number | EventInbox;
      } | null)
    | ({
        relationTo: 'maintenance-leases';
        value: number | MaintenanceLease;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  passportNumber?: T;
  nationality?: T;
  status?: T;
  failedLoginAttempts?: T;
  lockedUntil?: T;
  lastLoginAt?: T;
  emailVerifiedAt?: T;
  verificationExpiresAt?: T;
  phoneVerifiedAt?: T;
  deletedAt?: T;
  loyalty?:
    | T
    | {
        tier?: T;
        points?: T;
        totalSpent?: T;
        tierAchievedAt?: T;
      };
  preferences?:
    | T
    | {
        preferredLocale?: T;
        preferredLanguage?: T;
        preferredCurrency?: T;
        preferredTimezone?: T;
        measurementSystem?: T;
        notifications?:
          | T
          | {
              email?: T;
              sms?: T;
              push?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  description?: T;
  hero?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  currency?: T;
  defaultLanguage?: T;
  timezone?: T;
  measurementSystem?: T;
  weekStart?: T;
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  description?: T;
  hero?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations_select".
 */
export interface AccommodationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  city?: T;
  rating?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  packageMode?: T;
  city?: T;
  destinations?: T;
  description?: T;
  hero?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  duration?:
    | T
    | {
        days?: T;
        nights?: T;
        durationMinutes?: T;
      };
  price?: T;
  availability?: T;
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  itinerary?:
    | T
    | {
        dayNumber?: T;
        title?: T;
        city?: T;
        description?: T;
        id?: T;
      };
  accommodations?:
    | T
    | {
        order?: T;
        property?: T;
        nights?: T;
        roomCategory?: T;
        boardBasis?: T;
        pricingUnit?: T;
        roomRates?:
          | T
          | {
              occupancy?: T;
              rateEGP?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  childPolicy?:
    | T
    | {
        childrenAllowed?: T;
        childSharingBedPercentage?: T;
        childExtraBedPercentage?: T;
      };
  policies?: T;
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  schedules?:
    | T
    | {
        startTime?: T;
        defaultCapacity?: T;
        label?: T;
        id?: T;
      };
  blackouts?:
    | T
    | {
        date?: T;
        startTime?: T;
        reason?: T;
        id?: T;
      };
  priceOverrides?:
    | T
    | {
        date?: T;
        startTime?: T;
        priceEGP?: T;
        reason?: T;
        id?: T;
      };
  _slotsPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingNumber?: T;
  idempotencyKey?: T;
  user?: T;
  experience?: T;
  departureSlot?: T;
  status?: T;
  travelers?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        dateOfBirth?: T;
        passportNumber?: T;
        nationality?: T;
        type?: T;
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  completionAt?: T;
  destinationTimezone?: T;
  paymentWindowExpiresAt?: T;
  pricingSnapshot?:
    | T
    | {
        version?: T;
        basePriceEGP?: T;
        promotionDiscountEGP?: T;
        couponDiscountEGP?: T;
        loyaltyDiscountEGP?: T;
        subtotalEGP?: T;
        taxes?: T;
        fees?: T;
        totalAmountEGP?: T;
        displayCurrency?: T;
        displayAmount?: T;
        exchangeRate?: T;
        exchangeProvider?: T;
        exchangeRateTimestamp?: T;
        roundingStrategy?: T;
        currencyDecimals?: T;
      };
  pointsEarned?: T;
  paymentId?: T;
  pickupLocation?:
    | T
    | {
        label?: T;
        address?: T;
        latitude?: T;
        longitude?: T;
        source?: T;
        instructions?: T;
      };
  notes?: T;
  source?: T;
  version?: T;
  paymentStatus?: T;
  amountPaid?: T;
  outstandingBalance?: T;
  capacityHold?: T;
  pointHold?: T;
  paymentAttempts?: T;
  timeline?: T;
  auditTrail?: T;
  documents?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-ledger_select".
 */
export interface PointLedgerSelect<T extends boolean = true> {
  user?: T;
  ledgerVersion?: T;
  referenceType?: T;
  referenceId?: T;
  type?: T;
  amount?: T;
  balance?: T;
  reason?: T;
  booking?: T;
  expiresAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates_select".
 */
export interface ExchangeRatesSelect<T extends boolean = true> {
  fromCurrency?: T;
  toCurrency?: T;
  rate?: T;
  source?: T;
  lastUpdate?: T;
  lastSuccess?: T;
  lastAttempt?: T;
  lastError?: T;
  syncStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies_select".
 */
export interface CurrenciesSelect<T extends boolean = true> {
  isoCode?: T;
  numericCode?: T;
  name?: T;
  symbol?: T;
  nativeSymbol?: T;
  decimals?: T;
  flagCode?: T;
  isActive?: T;
  displayOrder?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-cache_select".
 */
export interface TranslationCacheSelect<T extends boolean = true> {
  originalHash?: T;
  sourceText?: T;
  language?: T;
  translatedText?: T;
  provider?: T;
  version?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-audit-logs_select".
 */
export interface AdminAuditLogsSelect<T extends boolean = true> {
  auditId?: T;
  adminUser?: T;
  adminEmail?: T;
  action?: T;
  targetDomain?: T;
  targetId?: T;
  reason?: T;
  metadata?: T;
  executedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-notification-preferences_select".
 */
export interface CustomerNotificationPreferencesSelect<T extends boolean = true> {
  customer?: T;
  marketingEmail?: T;
  marketingSMS?: T;
  marketingPush?: T;
  bookingEmail?: T;
  bookingSMS?: T;
  bookingPush?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-travelers_select".
 */
export interface CustomerTravelersSelect<T extends boolean = true> {
  customer?: T;
  firstName?: T;
  lastName?: T;
  dateOfBirth?: T;
  passportNumber?: T;
  relationship?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboard-projections_select".
 */
export interface DashboardProjectionsSelect<T extends boolean = true> {
  projectionId?: T;
  customer?: T;
  projectionJson?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  faqId?: T;
  category?: T;
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-logs_select".
 */
export interface MaintenanceLogsSelect<T extends boolean = true> {
  executionId?: T;
  correlationId?: T;
  jobName?: T;
  priority?: T;
  startedBy?: T;
  status?: T;
  itemsProcessed?: T;
  itemsFailed?: T;
  durationMs?: T;
  jobVersion?: T;
  engineVersion?: T;
  errorDetails?: T;
  executedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery_select".
 */
export interface MediaGallerySelect<T extends boolean = true> {
  mediaId?: T;
  altText?: T;
  fileUrl?: T;
  mimeType?: T;
  format?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-logs_select".
 */
export interface NotificationLogsSelect<T extends boolean = true> {
  notificationId?: T;
  referenceType?: T;
  referenceId?: T;
  customer?: T;
  recipient?: T;
  channel?: T;
  category?: T;
  priority?: T;
  templateId?: T;
  templateData?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  sentAt?: T;
  nextAttemptAt?: T;
  lastAttemptAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageId?: T;
  slug?: T;
  title?: T;
  status?: T;
  blocksJson?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-transactions_select".
 */
export interface PaymentTransactionsSelect<T extends boolean = true> {
  transactionId?: T;
  bookingId?: T;
  customerId?: T;
  version?: T;
  provider?: T;
  status?: T;
  session?: T;
  attempts?: T;
  webhookLedger?: T;
  auditTrail?: T;
  gatewayReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  postId?: T;
  slug?: T;
  title?: T;
  excerpt?: T;
  bodyHtml?: T;
  category?: T;
  authorName?: T;
  readTimeMinutes?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  redirectId?: T;
  oldSlug?: T;
  newSlug?: T;
  statusCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewId?: T;
  experience?: T;
  customer?: T;
  booking?: T;
  rating?: T;
  comment?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  couponId?: T;
  code?: T;
  discountType?: T;
  discountValue?: T;
  maxDiscountEGP?: T;
  minSpendEGP?: T;
  usageLimit?: T;
  usageCount?: T;
  status?: T;
  validFrom?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  name?: T;
  nativeName?: T;
  code?: T;
  isRTL?: T;
  isActive?: T;
  isDefault?: T;
  displayOrder?: T;
  preferredDisplayCurrency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departure-slots_select".
 */
export interface DepartureSlotsSelect<T extends boolean = true> {
  departureId?: T;
  experience?: T;
  date?: T;
  startTime?: T;
  priceOverrideEGP?: T;
  capacityTotal?: T;
  capacityReserved?: T;
  capacitySold?: T;
  capacityAvailable?: T;
  version?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-outbox_select".
 */
export interface EventOutboxSelect<T extends boolean = true> {
  eventId?: T;
  correlationId?: T;
  causationId?: T;
  eventType?: T;
  eventVersion?: T;
  aggregateType?: T;
  aggregateId?: T;
  payload?: T;
  status?: T;
  retryCount?: T;
  nextRetryAt?: T;
  errorMessage?: T;
  publishedAt?: T;
  occurredAt?: T;
  workerId?: T;
  lockExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-inbox_select".
 */
export interface EventInboxSelect<T extends boolean = true> {
  idempotencyKey?: T;
  processedEventId?: T;
  subscriberName?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-leases_select".
 */
export interface MaintenanceLeasesSelect<T extends boolean = true> {
  jobName?: T;
  workerId?: T;
  leaseExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings".
 */
export interface SystemSetting {
  id: number;
  /**
   * Standard VAT percentage (e.g. 14 for 14%)
   */
  vatRate: number;
  /**
   * Are experience base catalog prices inclusive of VAT?
   */
  pricesIncludeVat?: boolean | null;
  /**
   * Toggle standard VAT calculation on/off in pricing calculations
   */
  vatEnabled?: boolean | null;
  /**
   * Core system base currency (Locked to EGP)
   */
  baseCurrency: number | Currency;
  /**
   * Default currency to display to users (e.g., EGP)
   */
  defaultDisplayCurrency: number | Currency;
  autoSyncExchangeRates?: boolean | null;
  /**
   * Frequency of exchange rate synchronization (used by Cron/Scheduler, not by Pipeline)
   */
  exchangeSyncInterval?: number | null;
  exchangeRateCacheTtl?: number | null;
  /**
   * Designated operational email addresses to receive new booking requests and BNPL review alerts
   */
  bookingNotificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Configure official sender identities and reply-to destinations for business communication channels.
   */
  emailSenderSettings: {
    reservationIdentity: {
      fromName: string;
      fromEmail: string;
      replyTo: string;
    };
    loyaltyIdentity: {
      fromName: string;
      fromEmail: string;
      replyTo: string;
    };
    securityIdentity?: {
      fromName?: string | null;
      fromEmail?: string | null;
      replyTo?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Single Source of Truth for Loyalty Program Business Policy Configuration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-settings".
 */
export interface LoyaltySetting {
  id: number;
  /**
   * Sequential version number stored in point ledger metadata for historical auditing
   */
  version: number;
  /**
   * Core system loyalty program identifier (e.g., LAUBE_LOYALTY)
   */
  programCode: string;
  /**
   * Human-readable title displayed in customer portal
   */
  name: string;
  /**
   * Standard loyalty points earned per 1 EGP base spend
   */
  baseEarnRate: number;
  /**
   * Number of points per discount unit (e.g., 100 points)
   */
  redemptionPointsUnit: number;
  /**
   * EGP monetary discount value per points unit (e.g., 10 EGP per 100 points)
   */
  redemptionValueEGP: number;
  /**
   * Minimum points balance required before customer can redeem
   */
  minRedemptionPoints: number;
  /**
   * Forces redemption points to be multiples of this step (e.g. 50 points)
   */
  redemptionStepUnit?: number | null;
  /**
   * Maximum percentage of total booking EGP payable via points (e.g. 80%)
   */
  maxRedemptionPercent: number;
  /**
   * Optional absolute upper limit in EGP discount per booking (e.g., 5000 EGP)
   */
  maxRedemptionFixedEGP?: number | null;
  /**
   * If checked, customer can choose any custom point amount up to limit
   */
  allowPartialRedemption?: boolean | null;
  /**
   * Loyalty points granted upon new customer account creation
   */
  welcomeBonus: number;
  /**
   * Rolling validity period for earned points in months (e.g. 12 months)
   */
  expirationMonths: number;
  /**
   * Welcome and Tier Upgrade bonuses do not expire under rolling expiration
   */
  bonusNeverExpires?: boolean | null;
  tiers: {
    tier: string;
    label: string;
    minSpentEGP: number;
    earnMultiplier: number;
    upgradeBonus: number;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-settings_select".
 */
export interface SystemSettingsSelect<T extends boolean = true> {
  vatRate?: T;
  pricesIncludeVat?: T;
  vatEnabled?: T;
  baseCurrency?: T;
  defaultDisplayCurrency?: T;
  autoSyncExchangeRates?: T;
  exchangeSyncInterval?: T;
  exchangeRateCacheTtl?: T;
  bookingNotificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  emailSenderSettings?:
    | T
    | {
        reservationIdentity?:
          | T
          | {
              fromName?: T;
              fromEmail?: T;
              replyTo?: T;
            };
        loyaltyIdentity?:
          | T
          | {
              fromName?: T;
              fromEmail?: T;
              replyTo?: T;
            };
        securityIdentity?:
          | T
          | {
              fromName?: T;
              fromEmail?: T;
              replyTo?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-settings_select".
 */
export interface LoyaltySettingsSelect<T extends boolean = true> {
  version?: T;
  programCode?: T;
  name?: T;
  baseEarnRate?: T;
  redemptionPointsUnit?: T;
  redemptionValueEGP?: T;
  minRedemptionPoints?: T;
  redemptionStepUnit?: T;
  maxRedemptionPercent?: T;
  maxRedemptionFixedEGP?: T;
  allowPartialRedemption?: T;
  welcomeBonus?: T;
  expirationMonths?: T;
  bonusNeverExpires?: T;
  tiers?:
    | T
    | {
        tier?: T;
        label?: T;
        minSpentEGP?: T;
        earnMultiplier?: T;
        upgradeBonus?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}