/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    media: Media;
    countries: Country;
    cities: City;
    experiences: Experience;
    bookings: Booking;
    'point-ledger': PointLedger;
    'exchange-rates': ExchangeRate;
    currencies: Currency;
    'translation-cache': TranslationCache;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'point-ledger': PointLedgerSelect<false> | PointLedgerSelect<true>;
    'exchange-rates': ExchangeRatesSelect<false> | ExchangeRatesSelect<true>;
    currencies: CurrenciesSelect<false> | CurrenciesSelect<true>;
    'translation-cache': TranslationCacheSelect<false> | TranslationCacheSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar' | 'fr') | ('en' | 'ar' | 'fr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar' | 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'super_admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  status: 'active' | 'inactive' | 'suspended' | 'pending_verification' | 'pending_deletion' | 'deleted';
  failedLoginAttempts?: number | null;
  lockedUntil?: string | null;
  lastLoginAt?: string | null;
  emailVerifiedAt?: string | null;
  phoneVerifiedAt?: string | null;
  deletedAt?: string | null;
  loyalty: {
    /**
     * Tier is managed by LoyaltyService
     */
    tier: 'explorer' | 'voyager' | 'elite';
    /**
     * Cached value - source of truth is PointLedger
     */
    points?: number | null;
    /**
     * Total spent in EGP - used for tier calculation
     */
    totalSpent?: number | null;
    tierAchievedAt?: string | null;
  };
  preferences?: {
    /**
     * E.g., en-US, ar-EG. Controls dates, numbers, and separators.
     */
    preferredLocale?: string | null;
    preferredLanguage?: string | null;
    /**
     * Must match an active ISO Code in Currencies catalog
     */
    preferredCurrency?: string | null;
    preferredTimezone?: string | null;
    measurementSystem?: ('metric' | 'imperial') | null;
    notifications?: {
      email?: boolean | null;
      sms?: boolean | null;
      push?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  slug: string;
  /**
   * ISO 3166-1 alpha-2 country code
   */
  code: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  slug: string;
  country: number | Country;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  slug: string;
  type: 'package' | 'daily_tour';
  city: number | City;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  duration: {
    days: number;
    nights?: number | null;
  };
  /**
   * Base price in EGP
   */
  price: number;
  availability: 'available' | 'sold_out' | 'coming_soon' | 'unavailable';
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  policies?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  bookingNumber: string;
  user: number | Customer;
  experience: number | Experience;
  /**
   * Status can only be changed through BookingService
   */
  status: 'draft' | 'pending_payment' | 'paid' | 'confirmed' | 'completed' | 'cancelled' | 'refunded';
  travelers: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    dateOfBirth?: string | null;
    passportNumber?: string | null;
    id?: string | null;
  }[];
  startDate: string;
  endDate: string;
  /**
   * Immutable financial record of the booking
   */
  pricingSnapshot: {
    version?: number | null;
    basePriceEGP: number;
    promotionDiscountEGP?: number | null;
    couponDiscountEGP?: number | null;
    loyaltyDiscountEGP?: number | null;
    subtotalEGP: number;
    taxes?: number | null;
    fees?: number | null;
    totalAmountEGP: number;
    displayCurrency: string;
    displayAmount: number;
    exchangeRate: number;
    exchangeProvider?: string | null;
    exchangeRateTimestamp?: string | null;
    roundingStrategy?: string | null;
    currencyDecimals?: number | null;
  };
  /**
   * Calculated by LoyaltyService
   */
  pointsEarned?: number | null;
  paymentId?: string | null;
  notes?: string | null;
  source?: ('website' | 'admin' | 'api' | 'partner' | 'affiliate') | null;
  version?: number | null;
  /**
   * Active/Committed capacity hold entity
   */
  capacityHold?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Active/Committed loyalty point hold entity
   */
  pointHold?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Ledger of all payment attempts
   */
  paymentAttempts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Customer-facing lifecycle timeline
   */
  timeline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * System audit log entries
   */
  auditTrail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * References to generated documents (Invoice, Voucher, Receipt)
   */
  documents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional booking data
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable ledger of all loyalty point transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-ledger".
 */
export interface PointLedger {
  id: number;
  user: number | Customer;
  ledgerVersion: number;
  referenceType?: ('booking' | 'admin_ticket' | 'system_welcome' | 'expiration_scan') | null;
  referenceId?: string | null;
  type:
    | 'earn'
    | 'earned'
    | 'redeem'
    | 'redeemed'
    | 'refund'
    | 'refunded'
    | 'reverse'
    | 'reversed'
    | 'welcome_bonus'
    | 'tier_bonus'
    | 'manual_adjustment'
    | 'expiration'
    | 'expired';
  /**
   * Positive for earning/bonus, negative for spending/reversal
   */
  amount: number;
  /**
   * Running balance after this transaction
   */
  balance: number;
  reason: string;
  booking?: (number | null) | Booking;
  /**
   * Expiration date for earned points
   */
  expiresAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Live Financial Data for Exchange Rates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates".
 */
export interface ExchangeRate {
  id: number;
  /**
   * Base currency ISO code (e.g. EGP)
   */
  fromCurrency: string;
  /**
   * Target currency ISO code (e.g. USD)
   */
  toCurrency: string;
  /**
   * Exchange rate from base currency
   */
  rate: number;
  source: 'OpenExchange' | 'ECB' | 'Fixer' | 'Manual';
  /**
   * Actual timestamp the rate was fetched/changed
   */
  lastUpdate?: string | null;
  /**
   * Last time this rate was successfully synced
   */
  lastSuccess?: string | null;
  /**
   * Last time a sync was attempted (whether success or fail)
   */
  lastAttempt?: string | null;
  /**
   * Reason for the last sync failure (e.g. Timeout)
   */
  lastError?: string | null;
  syncStatus?: ('synced' | 'failed' | 'stale') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Master Catalog of Currencies (Identity only, no live rates)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies".
 */
export interface Currency {
  id: number;
  /**
   * ISO 4217 Currency Code (e.g., USD, EUR, JPY)
   */
  isoCode: string;
  /**
   * ISO 4217 Numeric Code (e.g., 840 for USD)
   */
  numericCode: number;
  /**
   * Full name (e.g., US Dollar)
   */
  name: string;
  /**
   * Common symbol (e.g., $)
   */
  symbol: string;
  /**
   * Native symbol (e.g., US$)
   */
  nativeSymbol?: string | null;
  /**
   * Number of decimal places (e.g., 2 for USD, 0 for JPY)
   */
  decimals: number;
  /**
   * ISO 3166-1 alpha-2 Country Codes where this currency is used
   */
  countryCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable or disable this currency in the frontend
   */
  isActive?: boolean | null;
  displayOrder?: number | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Persistent versioned cache for translated text segments with TTL
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-cache".
 */
export interface TranslationCache {
  id: number;
  /**
   * SHA-256 hash of the original English source text
   */
  originalHash: string;
  sourceText: string;
  /**
   * Target locale code (e.g. ar, fr)
   */
  language: string;
  translatedText: string;
  /**
   * Translation engine used (e.g. google, libre, deepl)
   */
  provider: string;
  /**
   * Source document version at the time of translation
   */
  version: number;
  /**
   * Last time this translation was verified against the source version/hash
   */
  lastVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'point-ledger';
        value: number | PointLedger;
      } | null)
    | ({
        relationTo: 'exchange-rates';
        value: number | ExchangeRate;
      } | null)
    | ({
        relationTo: 'currencies';
        value: number | Currency;
      } | null)
    | ({
        relationTo: 'translation-cache';
        value: number | TranslationCache;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  status?: T;
  failedLoginAttempts?: T;
  lockedUntil?: T;
  lastLoginAt?: T;
  emailVerifiedAt?: T;
  phoneVerifiedAt?: T;
  deletedAt?: T;
  loyalty?:
    | T
    | {
        tier?: T;
        points?: T;
        totalSpent?: T;
        tierAchievedAt?: T;
      };
  preferences?:
    | T
    | {
        preferredLocale?: T;
        preferredLanguage?: T;
        preferredCurrency?: T;
        preferredTimezone?: T;
        measurementSystem?: T;
        notifications?:
          | T
          | {
              email?: T;
              sms?: T;
              push?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  description?: T;
  hero?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  description?: T;
  hero?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  city?: T;
  description?: T;
  hero?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  duration?:
    | T
    | {
        days?: T;
        nights?: T;
      };
  price?: T;
  availability?: T;
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  policies?: T;
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingNumber?: T;
  user?: T;
  experience?: T;
  status?: T;
  travelers?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        dateOfBirth?: T;
        passportNumber?: T;
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  pricingSnapshot?:
    | T
    | {
        version?: T;
        basePriceEGP?: T;
        promotionDiscountEGP?: T;
        couponDiscountEGP?: T;
        loyaltyDiscountEGP?: T;
        subtotalEGP?: T;
        taxes?: T;
        fees?: T;
        totalAmountEGP?: T;
        displayCurrency?: T;
        displayAmount?: T;
        exchangeRate?: T;
        exchangeProvider?: T;
        exchangeRateTimestamp?: T;
        roundingStrategy?: T;
        currencyDecimals?: T;
      };
  pointsEarned?: T;
  paymentId?: T;
  notes?: T;
  source?: T;
  version?: T;
  capacityHold?: T;
  pointHold?: T;
  paymentAttempts?: T;
  timeline?: T;
  auditTrail?: T;
  documents?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-ledger_select".
 */
export interface PointLedgerSelect<T extends boolean = true> {
  user?: T;
  ledgerVersion?: T;
  referenceType?: T;
  referenceId?: T;
  type?: T;
  amount?: T;
  balance?: T;
  reason?: T;
  booking?: T;
  expiresAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates_select".
 */
export interface ExchangeRatesSelect<T extends boolean = true> {
  fromCurrency?: T;
  toCurrency?: T;
  rate?: T;
  source?: T;
  lastUpdate?: T;
  lastSuccess?: T;
  lastAttempt?: T;
  lastError?: T;
  syncStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies_select".
 */
export interface CurrenciesSelect<T extends boolean = true> {
  isoCode?: T;
  numericCode?: T;
  name?: T;
  symbol?: T;
  nativeSymbol?: T;
  decimals?: T;
  countryCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  isActive?: T;
  displayOrder?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translation-cache_select".
 */
export interface TranslationCacheSelect<T extends boolean = true> {
  originalHash?: T;
  sourceText?: T;
  language?: T;
  translatedText?: T;
  provider?: T;
  version?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}