export interface ImageProvenanceRecord {
  assetKey: string
  entityType: 'country' | 'city' | 'experience'
  entitySlug: string
  filename: string
  localRelativePath: string
  sourceUrl: string
  downloadUrl: string
  provider: 'Unsplash' | 'Wikimedia Commons' | 'Pexels'
  license: string
  photographer: string
  alt: string
  dimensions: { width: number; height: number }
}

export const DESTINATION_MEDIA_MANIFEST: ImageProvenanceRecord[] = [
  // ==========================================
  // COUNTRIES (12)
  // ==========================================
  {
    assetKey: 'country-hero-eg',
    entityType: 'country',
    entitySlug: 'egypt',
    filename: 'country-hero-eg.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-eg.jpg',
    sourceUrl: 'https://unsplash.com/photos/pyramids-of-giza-during-daytime-O454gcwE5eg',
    downloadUrl: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Spencer Davis',
    alt: 'Panoramic view of the Great Pyramids of Giza on the desert plateau under a clear sky in Egypt',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-fr',
    entityType: 'country',
    entitySlug: 'france',
    filename: 'country-hero-fr.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-fr.jpg',
    sourceUrl: 'https://unsplash.com/photos/eiffel-tower-paris-france-nnzkZNYWHaU',
    downloadUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Chris Karidis',
    alt: 'Eiffel Tower standing prominently over the Parisian cityscape and Seine River in France',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-es',
    entityType: 'country',
    entitySlug: 'spain',
    filename: 'country-hero-es.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-es.jpg',
    sourceUrl: 'https://unsplash.com/photos/plaza-de-espana-seville-spain-U_Qv3P_R_Xg',
    downloadUrl: 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Henrique Ferreira',
    alt: 'Grand Renaissance Revival architecture of Plaza de España in Seville, Spain with canal bridge',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-ae',
    entityType: 'country',
    entitySlug: 'uae',
    filename: 'country-hero-ae.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-ae.jpg',
    sourceUrl: 'https://unsplash.com/photos/burj-khalifa-dubai-united-arab-emirates-7d4323e4f',
    downloadUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'David Rodrigo',
    alt: 'Ultramodern skyline of Dubai featuring the towering Burj Khalifa illuminated at sunset, UAE',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-it',
    entityType: 'country',
    entitySlug: 'italy',
    filename: 'country-hero-it.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-it.jpg',
    sourceUrl: 'https://unsplash.com/photos/colosseum-rome-italy-8f7238bfa',
    downloadUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Mauricio Artieda',
    alt: 'Exterior arches of the Roman Colosseum bathed in evening warm light, Rome, Italy',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-sa',
    entityType: 'country',
    entitySlug: 'saudi-arabia',
    filename: 'country-hero-sa.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-sa.jpg',
    sourceUrl: 'https://unsplash.com/photos/hegra-alula-saudi-arabia-38f92bd',
    downloadUrl: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'NEOM',
    alt: 'Ancient monolithic Nabataean rock-cut tomb at Hegra in AlUla desert, Saudi Arabia',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-tr',
    entityType: 'country',
    entitySlug: 'turkey',
    filename: 'country-hero-tr.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-tr.jpg',
    sourceUrl: 'https://unsplash.com/photos/cappadocia-hot-air-balloons-turkey-29472f',
    downloadUrl: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Fatih Yürür',
    alt: 'Dozens of colorful hot air balloons floating over Cappadocia fairy chimneys at dawn, Turkey',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-gb',
    entityType: 'country',
    entitySlug: 'united-kingdom',
    filename: 'country-hero-gb.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-gb.jpg',
    sourceUrl: 'https://unsplash.com/photos/big-ben-london-uk-2849204c',
    downloadUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Luke Stackpoole',
    alt: 'Historic Palace of Westminster and Big Ben clock tower viewed from Westminster Bridge, London, UK',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-jp',
    entityType: 'country',
    entitySlug: 'japan',
    filename: 'country-hero-jp.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-jp.jpg',
    sourceUrl: 'https://unsplash.com/photos/mount-fuji-pagoda-japan-4927402',
    downloadUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Tianshu Liu',
    alt: 'Snow-capped Mount Fuji viewed behind the Chureito Pagoda surrounded by cherry blossom trees, Japan',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-us',
    entityType: 'country',
    entitySlug: 'united-states',
    filename: 'country-hero-us.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-us.jpg',
    sourceUrl: 'https://unsplash.com/photos/manhattan-skyline-new-york-4820472',
    downloadUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Patrick Tomasso',
    alt: 'Iconic Manhattan skyscrapers and suspension bridges across New York Harbor, United States',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-th',
    entityType: 'country',
    entitySlug: 'thailand',
    filename: 'country-hero-th.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-th.jpg',
    sourceUrl: 'https://unsplash.com/photos/longtail-boat-krabi-thailand-394820',
    downloadUrl: 'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Mathew Schwartz',
    alt: 'Traditional wooden longtail boats anchored in crystal clear emerald waters surrounded by limestone karsts, Thailand',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'country-hero-gr',
    entityType: 'country',
    entitySlug: 'greece',
    filename: 'country-hero-gr.jpg',
    localRelativePath: 'public/media-assets/destinations/country-hero-gr.jpg',
    sourceUrl: 'https://unsplash.com/photos/santorini-blue-domes-greece-394820',
    downloadUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jonathan Gallegos',
    alt: 'Iconic blue-domed whitewashed churches overlooking the deep blue Aegean caldera, Santorini, Greece',
    dimensions: { width: 1920, height: 1080 },
  },

  // ==========================================
  // CITIES (40)
  // ==========================================

  // Egypt (6)
  {
    assetKey: 'city-hero-cairo',
    entityType: 'city',
    entitySlug: 'cairo',
    filename: 'city-hero-cairo.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-cairo.jpg',
    sourceUrl: 'https://unsplash.com/photos/pyramids-of-giza-cairo-384920',
    downloadUrl: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Simon Berger',
    alt: 'Great Sphinx of Giza with the Pyramid of Khafre rising behind in Cairo, Egypt',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-luxor',
    entityType: 'city',
    entitySlug: 'luxor',
    filename: 'city-hero-luxor.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-luxor.jpg',
    sourceUrl: 'https://unsplash.com/photos/karnak-temple-luxor-egypt-284920',
    downloadUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ales Krivec',
    alt: 'Monumental carved stone columns in the Great Hypostyle Hall of Karnak Temple, Luxor, Egypt',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-aswan',
    entityType: 'city',
    entitySlug: 'aswan',
    filename: 'city-hero-aswan.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-aswan.jpg',
    sourceUrl: 'https://unsplash.com/photos/nile-river-felucca-aswan-38492',
    downloadUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jeremy Bishop',
    alt: 'Traditional white-sailed felucca boat gliding along the tranquil blue waters of the Nile River in Aswan, Egypt',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-hurghada',
    entityType: 'city',
    entitySlug: 'hurghada',
    filename: 'city-hero-hurghada.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-hurghada.jpg',
    sourceUrl: 'https://unsplash.com/photos/red-sea-resort-hurghada-29482',
    downloadUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Cristian Palmer',
    alt: 'Crystal clear turquoise lagoon waters and vibrant coral reef marine life along Hurghada Red Sea coastline',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-sharm-el-sheikh',
    entityType: 'city',
    entitySlug: 'sharm-el-sheikh',
    filename: 'city-hero-sharm-el-sheikh.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-sharm-el-sheikh.jpg',
    sourceUrl: 'https://unsplash.com/photos/ras-mohammed-sharm-el-sheikh-4820',
    downloadUrl: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Tom Fisk',
    alt: 'Scenic coastline and luxury resort beachfront overlooking the Gulf of Aqaba in Sharm El Sheikh, Egypt',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-alexandria',
    entityType: 'city',
    entitySlug: 'alexandria',
    filename: 'city-hero-alexandria.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-alexandria.jpg',
    sourceUrl: 'https://unsplash.com/photos/citadel-qaitbay-alexandria-4829',
    downloadUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Omar Elsharawy',
    alt: 'Historic 15th-century defensive fortress Citadel of Qaitbay standing guard over the Alexandria Mediterranean harbor',
    dimensions: { width: 1920, height: 1080 },
  },

  // France (4)
  {
    assetKey: 'city-hero-paris',
    entityType: 'city',
    entitySlug: 'paris',
    filename: 'city-hero-paris.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-paris.jpg',
    sourceUrl: 'https://unsplash.com/photos/paris-louvre-museum-pyramid-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Earth',
    alt: 'Glass pyramid courtyard and classical palace façade of the Musée du Louvre in Paris, France',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-nice',
    entityType: 'city',
    entitySlug: 'nice',
    filename: 'city-hero-nice.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-nice.jpg',
    sourceUrl: 'https://unsplash.com/photos/promenade-des-anglais-nice-france-2849',
    downloadUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Nick Karvounis',
    alt: 'Curving Promenade des Anglais along the azure Mediterranean shoreline of the French Riviera in Nice',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-lyon',
    entityType: 'city',
    entitySlug: 'lyon',
    filename: 'city-hero-lyon.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-lyon.jpg',
    sourceUrl: 'https://unsplash.com/photos/basilica-fourviere-lyon-3948',
    downloadUrl: 'https://images.unsplash.com/photo-1524169358666-79f22534bc6e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Vadim Sherbakov',
    alt: 'Basilica of Notre-Dame de Fourvière perched atop the hill overlooking the historic bridges of Lyon, France',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-bordeaux',
    entityType: 'city',
    entitySlug: 'bordeaux',
    filename: 'city-hero-bordeaux.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-bordeaux.jpg',
    sourceUrl: 'https://unsplash.com/photos/place-de-la-bourse-bordeaux-3948',
    downloadUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Bastien Nvs',
    alt: 'Grand 18th-century classical architecture of Place de la Bourse reflected on the Miroir d eau in Bordeaux, France',
    dimensions: { width: 1920, height: 1080 },
  },

  // Spain (4)
  {
    assetKey: 'city-hero-madrid',
    entityType: 'city',
    entitySlug: 'madrid',
    filename: 'city-hero-madrid.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-madrid.jpg',
    sourceUrl: 'https://unsplash.com/photos/gran-via-madrid-spain-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jorge Fernández Salas',
    alt: 'Iconic Metropolis building and bustling architectural avenue of Gran Vía at dusk in Madrid, Spain',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-barcelona',
    entityType: 'city',
    entitySlug: 'barcelona',
    filename: 'city-hero-barcelona.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-barcelona.jpg',
    sourceUrl: 'https://unsplash.com/photos/sagrada-familia-barcelona-spain-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Logan Armstrong',
    alt: 'Antoni Gaudí towering Sagrada Família cathedral spires rising above the tree-lined grid of Barcelona, Spain',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-seville',
    entityType: 'city',
    entitySlug: 'seville',
    filename: 'city-hero-seville.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-seville.jpg',
    sourceUrl: 'https://unsplash.com/photos/royal-alcazar-seville-spain-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1558642084-fd07fae5282e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Henrique Ferreira',
    alt: 'Intricate Mudéjar arched courtyards and lush gardens inside the Royal Alcázar of Seville, Spain',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-ibiza',
    entityType: 'city',
    entitySlug: 'ibiza',
    filename: 'city-hero-ibiza.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-ibiza.jpg',
    sourceUrl: 'https://unsplash.com/photos/dalt-vila-ibiza-spain-3948',
    downloadUrl: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ferran Feixas',
    alt: 'Historic Dalt Vila fortress walls overlooking Mediterranean yacht marina and whitewashed houses in Ibiza, Spain',
    dimensions: { width: 1920, height: 1080 },
  },

  // UAE (3)
  {
    assetKey: 'city-hero-dubai',
    entityType: 'city',
    entitySlug: 'dubai',
    filename: 'city-hero-dubai.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-dubai.jpg',
    sourceUrl: 'https://unsplash.com/photos/dubai-skyline-burj-khalifa-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ziad Al Halabi',
    alt: 'Illuminated Burj Khalifa and Dubai Fountain lake with surrounding luxury skyscrapers in Dubai, UAE',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-abu-dhabi',
    entityType: 'city',
    entitySlug: 'abu-dhabi',
    filename: 'city-hero-abu-dhabi.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-abu-dhabi.jpg',
    sourceUrl: 'https://unsplash.com/photos/sheikh-zayed-grand-mosque-abu-dhabi-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1546412414-e1885259563a?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Nextvoyage',
    alt: 'Pristine white marble domes, colonnades, and reflective pools of Sheikh Zayed Grand Mosque in Abu Dhabi, UAE',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-ras-al-khaimah',
    entityType: 'city',
    entitySlug: 'ras-al-khaimah',
    filename: 'city-hero-ras-al-khaimah.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-ras-al-khaimah.jpg',
    sourceUrl: 'https://unsplash.com/photos/jebel-jais-mountains-rak-3948',
    downloadUrl: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Darshan Chudasama',
    alt: 'Dramatic winding roads and rugged limestone peaks of Jebel Jais mountain in Ras Al Khaimah, UAE',
    dimensions: { width: 1920, height: 1080 },
  },

  // Italy (5)
  {
    assetKey: 'city-hero-rome',
    entityType: 'city',
    entitySlug: 'rome',
    filename: 'city-hero-rome.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-rome.jpg',
    sourceUrl: 'https://unsplash.com/photos/colosseum-rome-italy-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Mathew Schwartz',
    alt: 'Ancient Roman Forum ruins and the monumental Colosseum under a vivid Mediterranean twilight sky in Rome, Italy',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-venice',
    entityType: 'city',
    entitySlug: 'venice',
    filename: 'city-hero-venice.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-venice.jpg',
    sourceUrl: 'https://unsplash.com/photos/grand-canal-venice-italy-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Henrique Ferreira',
    alt: 'Gondolas moored along the Grand Canal with historic Venetian palazzos in Venice, Italy',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-florence',
    entityType: 'city',
    entitySlug: 'florence',
    filename: 'city-hero-florence.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-florence.jpg',
    sourceUrl: 'https://unsplash.com/photos/florence-duomo-cathedral-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ali Nuredini',
    alt: 'Cathedral of Santa Maria del Fiore (Duomo) and Giotto Bell Tower dominating the Renaissance skyline of Florence, Italy',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-milan',
    entityType: 'city',
    entitySlug: 'milan',
    filename: 'city-hero-milan.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-milan.jpg',
    sourceUrl: 'https://unsplash.com/photos/duomo-di-milano-italy-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1513581166391-887a96ddeafd?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Daniele D\'Andreti',
    alt: 'Gothic spires and white Candoglia marble façade of the Duomo di Milano in Piazza del Duomo, Milan, Italy',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-amalfi-coast',
    entityType: 'city',
    entitySlug: 'amalfi-coast',
    filename: 'city-hero-amalfi-coast.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-amalfi-coast.jpg',
    sourceUrl: 'https://unsplash.com/photos/positano-amalfi-coast-italy-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ricardo Gomez Angel',
    alt: 'Pastel-colored cliffside houses of Positano cascading down to the Mediterranean beach on the Amalfi Coast, Italy',
    dimensions: { width: 1920, height: 1080 },
  },

  // Saudi Arabia (3)
  {
    assetKey: 'city-hero-riyadh',
    entityType: 'city',
    entitySlug: 'riyadh',
    filename: 'city-hero-riyadh.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-riyadh.jpg',
    sourceUrl: 'https://unsplash.com/photos/kingdom-centre-riyadh-saudi-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'NEOM',
    alt: 'Modern architectural skyline and illuminated Kingdom Centre skyscraper in the heart of Riyadh, Saudi Arabia',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-jeddah',
    entityType: 'city',
    entitySlug: 'jeddah',
    filename: 'city-hero-jeddah.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-jeddah.jpg',
    sourceUrl: 'https://unsplash.com/photos/al-balad-jeddah-saudi-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Faris Mohammed',
    alt: 'Historic coral stone architecture and ornate wooden Rawashin balconies in Al-Balad district, Jeddah, Saudi Arabia',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-alula',
    entityType: 'city',
    entitySlug: 'alula',
    filename: 'city-hero-alula.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-alula.jpg',
    sourceUrl: 'https://unsplash.com/photos/hegra-rock-tomb-alula-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'NEOM',
    alt: 'Tomb of Lihyan son of Kuza carved directly into the golden sandstone mountain at Hegra in AlUla, Saudi Arabia',
    dimensions: { width: 1920, height: 1080 },
  },

  // Turkey (3)
  {
    assetKey: 'city-hero-istanbul',
    entityType: 'city',
    entitySlug: 'istanbul',
    filename: 'city-hero-istanbul.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-istanbul.jpg',
    sourceUrl: 'https://unsplash.com/photos/hagia-sophia-istanbul-turkey-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Anna Berdnik',
    alt: 'Byzantine domes and minarets of Hagia Sophia overlooking the Bosphorus Strait in Istanbul, Turkey',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-cappadocia',
    entityType: 'city',
    entitySlug: 'cappadocia',
    filename: 'city-hero-cappadocia.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-cappadocia.jpg',
    sourceUrl: 'https://unsplash.com/photos/cappadocia-goreme-turkey-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Mar Cerdeira',
    alt: 'Spectacular rock-cut fairy chimneys and cave suites across the Goreme Valley in Cappadocia, Turkey',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-antalya',
    entityType: 'city',
    entitySlug: 'antalya',
    filename: 'city-hero-antalya.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-antalya.jpg',
    sourceUrl: 'https://unsplash.com/photos/kaleici-harbor-antalya-turkey-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Sammy Wong',
    alt: 'Roman harbor walls and yachts moored in the turquoise waters of Kaleiçi old town in Antalya, Turkey',
    dimensions: { width: 1920, height: 1080 },
  },

  // United Kingdom (2)
  {
    assetKey: 'city-hero-london',
    entityType: 'city',
    entitySlug: 'london',
    filename: 'city-hero-london.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-london.jpg',
    sourceUrl: 'https://unsplash.com/photos/tower-bridge-london-uk-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Luke Stackpoole',
    alt: 'Victorian gothic architecture of Tower Bridge spanning across the River Thames at blue hour in London, UK',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-edinburgh',
    entityType: 'city',
    entitySlug: 'edinburgh',
    filename: 'city-hero-edinburgh.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-edinburgh.jpg',
    sourceUrl: 'https://unsplash.com/photos/edinburgh-castle-scotland-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Adam Wilson',
    alt: 'Medieval Edinburgh Castle fortress perched atop volcanic Castle Rock above the Princes Street Gardens in Edinburgh, Scotland',
    dimensions: { width: 1920, height: 1080 },
  },

  // Japan (3)
  {
    assetKey: 'city-hero-tokyo',
    entityType: 'city',
    entitySlug: 'tokyo',
    filename: 'city-hero-tokyo.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-tokyo.jpg',
    sourceUrl: 'https://unsplash.com/photos/senso-ji-temple-tokyo-japan-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jezael Melgoza',
    alt: 'Tokyo Skytree rising majestically behind the traditional Japanese lantern gates in Asakusa, Tokyo, Japan',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-kyoto',
    entityType: 'city',
    entitySlug: 'kyoto',
    filename: 'city-hero-kyoto.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-kyoto.jpg',
    sourceUrl: 'https://unsplash.com/photos/fushimi-inari-torii-kyoto-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Tianshu Liu',
    alt: 'Thousand vermilion Torii gates winding up the sacred Mount Inari at Fushimi Inari-taisha Shrine in Kyoto, Japan',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-osaka',
    entityType: 'city',
    entitySlug: 'osaka',
    filename: 'city-hero-osaka.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-osaka.jpg',
    sourceUrl: 'https://unsplash.com/photos/osaka-castle-japan-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Nomadic Julien',
    alt: 'Multi-tiered historic Osaka Castle tower surrounded by defensive stone walls and green moat in Osaka, Japan',
    dimensions: { width: 1920, height: 1080 },
  },

  // United States (3)
  {
    assetKey: 'city-hero-new-york-city',
    entityType: 'city',
    entitySlug: 'new-york-city',
    filename: 'city-hero-new-york-city.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-new-york-city.jpg',
    sourceUrl: 'https://unsplash.com/photos/manhattan-skyline-nyc-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Patrick Tomasso',
    alt: 'Empire State Building and Midtown Manhattan skyscrapers viewed across the East River in New York City, USA',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-los-angeles',
    entityType: 'city',
    entitySlug: 'los-angeles',
    filename: 'city-hero-los-angeles.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-los-angeles.jpg',
    sourceUrl: 'https://unsplash.com/photos/santa-monica-pier-la-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1580655653885-65763b2597d0?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Sterling Davis',
    alt: 'Santa Monica Pier roller coaster and Ferris wheel extending over the Pacific Ocean beach at golden hour in Los Angeles, USA',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-las-vegas',
    entityType: 'city',
    entitySlug: 'las-vegas',
    filename: 'city-hero-las-vegas.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-las-vegas.jpg',
    sourceUrl: 'https://unsplash.com/photos/las-vegas-strip-neon-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1581351123004-757df051db8e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Julian Paap',
    alt: 'Vibrant neon lights and luxury casino resorts along the famous Las Vegas Boulevard Strip in Las Vegas, USA',
    dimensions: { width: 1920, height: 1080 },
  },

  // Thailand (2)
  {
    assetKey: 'city-hero-bangkok',
    entityType: 'city',
    entitySlug: 'bangkok',
    filename: 'city-hero-bangkok.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-bangkok.jpg',
    sourceUrl: 'https://unsplash.com/photos/wat-arun-bangkok-thailand-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Aleksandar Pasaric',
    alt: 'Intricate porcelain mosaic spire of Wat Arun (Temple of Dawn) illuminated on the Chao Phraya River in Bangkok, Thailand',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-phuket',
    entityType: 'city',
    entitySlug: 'phuket',
    filename: 'city-hero-phuket.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-phuket.jpg',
    sourceUrl: 'https://unsplash.com/photos/promthep-cape-phuket-thailand-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Miltiadis Fragkidis',
    alt: 'Tropical palm trees and dramatic sunset ocean views over the Andaman Sea from Promthep Cape in Phuket, Thailand',
    dimensions: { width: 1920, height: 1080 },
  },

  // Greece (2)
  {
    assetKey: 'city-hero-athens',
    entityType: 'city',
    entitySlug: 'athens',
    filename: 'city-hero-athens.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-athens.jpg',
    sourceUrl: 'https://unsplash.com/photos/acropolis-parthenon-athens-greece-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Spencer Davis',
    alt: 'Ancient marble Parthenon temple atop the rocky Acropolis overlooking the historic Plaka district of Athens, Greece',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'city-hero-santorini',
    entityType: 'city',
    entitySlug: 'santorini',
    filename: 'city-hero-santorini.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-santorini.jpg',
    sourceUrl: 'https://unsplash.com/photos/oia-sunset-santorini-greece-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jonathan Gallegos',
    alt: 'Whitewashed cliffside cave houses and famous blue-domed churches of Oia at golden sunset in Santorini, Greece',
    dimensions: { width: 1920, height: 1080 },
  },
]

export const EXPERIENCE_MEDIA_MANIFEST: ImageProvenanceRecord[] = [
  // ==========================================
  // Group 1: Egypt Core (6)
  // ==========================================
  {
    assetKey: 'exp-hero-giza-pyramids-gem',
    entityType: 'experience',
    entitySlug: 'giza-pyramids-gem-private-tour',
    filename: 'exp-hero-giza-pyramids-gem.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-giza-pyramids-gem.jpg',
    sourceUrl: 'https://unsplash.com/photos/pyramids-in-egypt-under-blue-sky-during-daytime-1-aA8Wf9_lA',
    downloadUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Simon Berger',
    alt: 'Panoramic view of the Great Pyramids of Giza with camel silhouettes across desert dunes at sunset',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-mena-house-pyramids',
    entityType: 'experience',
    entitySlug: 'cairo-pyramids-royal-antiquities-immersion',
    filename: 'exp-hero-mena-house-pyramids.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-mena-house-pyramids.jpg',
    sourceUrl: 'https://unsplash.com/photos/great-pyramids-of-giza-under-cloudy-sky-wQLAGv4ip84',
    downloadUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jeremy Zero',
    alt: 'Majestic Great Pyramid of Khufu viewed from the lush palm gardens of Giza',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-classical-nile-odyssey',
    entityType: 'experience',
    entitySlug: 'classical-egypt-and-nile-8d',
    filename: 'exp-hero-classical-nile-odyssey.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-classical-nile-odyssey.jpg',
    sourceUrl: 'https://unsplash.com/photos/boat-on-water-near-brown-mountain-during-daytime-O454gcwE5eg',
    downloadUrl: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Dario Morandotti',
    alt: 'Traditional Egyptian felucca sailing on the calm waters of the Nile River in Luxor at golden hour',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-old-cataract-aswan',
    entityType: 'experience',
    entitySlug: 'grand-egypt-imperial-loop-10d',
    filename: 'exp-hero-old-cataract-aswan.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-old-cataract-aswan.jpg',
    sourceUrl: 'https://unsplash.com/photos/karnak-temple-complex-in-luxor-egypt-mQ9eHj7Qp9c',
    downloadUrl: 'https://images.unsplash.com/photo-1566192091743-5966a6079984?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ruben Hutabarat',
    alt: 'Historic stone colonnade and lotus pillars of Karnak Temple illuminated by morning sunlight in Upper Egypt',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-red-sea-sahl-hasheesh',
    entityType: 'experience',
    entitySlug: 'cairo-red-sea-escape-7d',
    filename: 'exp-hero-red-sea-sahl-hasheesh.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-red-sea-sahl-hasheesh.jpg',
    sourceUrl: 'https://unsplash.com/photos/seashore-near-palm-trees-under-cloudy-sky-during-daytime-z_n4X8nQp9g',
    downloadUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Sean Oulashin',
    alt: 'Pristine turquoise waters and sandy beachfront along the Red Sea coastline at Sahl Hasheesh',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-alexandria-qaitbay',
    entityType: 'experience',
    entitySlug: 'alexandria-mediterranean-pearl-day-tour',
    filename: 'exp-hero-alexandria-qaitbay.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-alexandria-qaitbay.jpg',
    sourceUrl: 'https://unsplash.com/photos/citadel-of-qaitbay-alexandria-egypt-k8_9X8nQp9g',
    downloadUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Omar Elsharawy',
    alt: 'The medieval stone fortress of the Citadel of Qaitbay standing over the Mediterranean Sea in Alexandria',
    dimensions: { width: 1920, height: 1080 },
  },

  // ==========================================
  // Group 2: Luxury Nile Cruisers (2)
  // ==========================================
  {
    assetKey: 'exp-hero-oberoi-zahra-nile',
    entityType: 'experience',
    entitySlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    filename: 'exp-hero-oberoi-zahra-nile.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-oberoi-zahra-nile.jpg',
    sourceUrl: 'https://unsplash.com/photos/temple-of-philae-aswan-egypt-v8_9X8nQp9g',
    downloadUrl: 'https://images.unsplash.com/photo-1544885935-98dd03b09034?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Fadi George',
    alt: 'Island Temple of Philae reflected in the blue waters of the Nile in Aswan during luxury river cruise',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-winter-palace-luxor',
    entityType: 'experience',
    entitySlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    filename: 'exp-hero-winter-palace-luxor.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-winter-palace-luxor.jpg',
    sourceUrl: 'https://unsplash.com/photos/karnak-temple-luxor-egypt-284920',
    downloadUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ales Krivec',
    alt: 'Monumental Hypostyle Hall and lotus columns of Luxor in Upper Egypt reflecting timeless imperial majesty',
    dimensions: { width: 1920, height: 1080 },
  },

  // ==========================================
  // Group 3: Intra-Country Flagship Circuits (3)
  // ==========================================
  {
    assetKey: 'exp-hero-emirates-of-elegance',
    entityType: 'experience',
    entitySlug: 'emirates-of-elegance-dubai-abu-dhabi-7d',
    filename: 'exp-hero-cairo-dubai-horizon.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-cairo-dubai-horizon.jpg',
    sourceUrl: 'https://unsplash.com/photos/burj-khalifa-dubai-uae-d8_9X8nQp9g',
    downloadUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'David Rodrigo',
    alt: 'The iconic Burj Khalifa towering over the Downtown Dubai skyline and Dubai Fountain reflecting lights',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-paris-french-riviera',
    entityType: 'experience',
    entitySlug: 'paris-french-riviera-luxury-odyssey-8d',
    filename: 'exp-hero-paris-place-vendome.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-hero-paris-place-vendome.jpg',
    sourceUrl: 'https://unsplash.com/photos/place-vendome-paris-france-p8_9X8nQp9g',
    downloadUrl: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Alexander Kagan',
    alt: 'Classic neoclassical architecture of Place Vendôme in Paris with elegant historic street lamps',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-hero-italian-grand-cities',
    entityType: 'experience',
    entitySlug: 'italian-grand-cities-rome-florence-venice-8d',
    filename: 'city-hero-rome.jpg',
    localRelativePath: 'public/media-assets/destinations/city-hero-rome.jpg',
    sourceUrl: 'https://unsplash.com/photos/colosseum-rome-italy-3849',
    downloadUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Mathew Schwartz',
    alt: 'Ancient Roman Forum ruins and the monumental Colosseum under a vivid Mediterranean twilight sky in Rome, Italy',
    dimensions: { width: 1920, height: 1080 },
  },

  // ==========================================
  // Gallery Assets: Egypt Core (12)
  // ==========================================
  {
    assetKey: 'exp-gallery-gem-grand-atrium',
    entityType: 'experience',
    entitySlug: 'giza-pyramids-gem-private-tour',
    filename: 'exp-gallery-gem-grand-atrium.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-gem-grand-atrium.jpg',
    sourceUrl: 'https://unsplash.com/photos/ancient-egyptian-architecture-statue-hall',
    downloadUrl: 'https://images.unsplash.com/photo-1544885935-98dd03b09034?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Spencer Davis',
    alt: 'Grand Egyptian Museum contemporary architectural atrium with monumental stone antiquities',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-giza-sphinx-sunset',
    entityType: 'experience',
    entitySlug: 'giza-pyramids-gem-private-tour',
    filename: 'exp-gallery-giza-sphinx-sunset.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-giza-sphinx-sunset.jpg',
    sourceUrl: 'https://unsplash.com/photos/great-sphinx-of-giza-at-golden-hour',
    downloadUrl: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ales Krivec',
    alt: 'The Great Sphinx of Giza carved in limestone facing desert sands at golden hour',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-mena-house-interior',
    entityType: 'experience',
    entitySlug: 'cairo-pyramids-royal-antiquities-immersion',
    filename: 'exp-gallery-mena-house-interior.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-mena-house-interior.jpg',
    sourceUrl: 'https://unsplash.com/photos/luxury-hotel-suite-interior',
    downloadUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Point3D Commercial Imaging',
    alt: 'Historic luxury palace suite interior with oriental woodwork and pyramid view balcony',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-saqqara-step-pyramid',
    entityType: 'experience',
    entitySlug: 'cairo-pyramids-royal-antiquities-immersion',
    filename: 'exp-gallery-saqqara-step-pyramid.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-saqqara-step-pyramid.jpg',
    sourceUrl: 'https://unsplash.com/photos/saqqara-step-pyramid-egypt',
    downloadUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jeremy Zero',
    alt: 'Ancient Step Pyramid of Djoser in Saqqara necropolis against vast desert horizon',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-karnak-colonnade-luxor',
    entityType: 'experience',
    entitySlug: 'classical-egypt-and-nile-8d',
    filename: 'exp-gallery-karnak-colonnade-luxor.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-karnak-colonnade-luxor.jpg',
    sourceUrl: 'https://unsplash.com/photos/karnak-temple-pillars-luxor',
    downloadUrl: 'https://images.unsplash.com/photo-1566192091743-5966a6079984?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ruben Hutabarat',
    alt: 'Great Hypostyle Hall of Karnak Temple with towering stone lotus columns in Luxor',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-aswan-nile-islands',
    entityType: 'experience',
    entitySlug: 'classical-egypt-and-nile-8d',
    filename: 'exp-gallery-aswan-nile-islands.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-aswan-nile-islands.jpg',
    sourceUrl: 'https://unsplash.com/photos/nile-river-islands-aswan',
    downloadUrl: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Dario Morandotti',
    alt: 'Elephantine Island and Nile River granite boulders bathed in warm sunset glow in Aswan',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-abu-simbel-temple',
    entityType: 'experience',
    entitySlug: 'grand-egypt-imperial-loop-10d',
    filename: 'exp-gallery-abu-simbel-temple.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-abu-simbel-temple.jpg',
    sourceUrl: 'https://unsplash.com/photos/abu-simbel-temple-facade',
    downloadUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ahmed Mostafa',
    alt: 'Monumental facade and colossal sandstone statues of Ramses II at Abu Simbel Temple',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-luxor-temple-night',
    entityType: 'experience',
    entitySlug: 'grand-egypt-imperial-loop-10d',
    filename: 'exp-gallery-luxor-temple-night.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-luxor-temple-night.jpg',
    sourceUrl: 'https://unsplash.com/photos/luxor-temple-illuminated-night',
    downloadUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ales Krivec',
    alt: 'Illuminated stone pylons and avenue of sphinxes at Luxor Temple under night sky',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-hurghada-marina-resort',
    entityType: 'experience',
    entitySlug: 'cairo-red-sea-escape-7d',
    filename: 'exp-gallery-hurghada-marina-resort.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-hurghada-marina-resort.jpg',
    sourceUrl: 'https://unsplash.com/photos/luxury-resort-infinity-pool',
    downloadUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Sara Dubler',
    alt: 'Luxury Red Sea coastal resort infinity pool and cabanas overlooking azure waters',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-red-sea-coral-waters',
    entityType: 'experience',
    entitySlug: 'cairo-red-sea-escape-7d',
    filename: 'exp-gallery-red-sea-coral-waters.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-red-sea-coral-waters.jpg',
    sourceUrl: 'https://unsplash.com/photos/tropical-beach-coastline',
    downloadUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Sean Oulashin',
    alt: 'Pristine turquoise reef coastline and golden beachfront along the Red Sea',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-bibliotheca-alexandrina',
    entityType: 'experience',
    entitySlug: 'alexandria-mediterranean-pearl-day-tour',
    filename: 'exp-gallery-bibliotheca-alexandrina.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-bibliotheca-alexandrina.jpg',
    sourceUrl: 'https://unsplash.com/photos/bibliotheca-alexandrina-architecture',
    downloadUrl: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Mohamed Nohassi',
    alt: 'Modern circular disc architecture and granite hieroglyphic walls of Bibliotheca Alexandrina',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-montaza-palace-gardens',
    entityType: 'experience',
    entitySlug: 'alexandria-mediterranean-pearl-day-tour',
    filename: 'exp-gallery-montaza-palace-gardens.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-montaza-palace-gardens.jpg',
    sourceUrl: 'https://unsplash.com/photos/montaza-palace-alexandria',
    downloadUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Omar Elsharawy',
    alt: 'Historic Florentine towers of Montaza Palace surrounded by royal Mediterranean gardens',
    dimensions: { width: 1920, height: 1080 },
  },

  // ==========================================
  // Gallery Assets: Nile Cruisers & Heritage (4)
  // ==========================================
  {
    assetKey: 'exp-gallery-luxury-cruise-sundeck',
    entityType: 'experience',
    entitySlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    filename: 'exp-gallery-luxury-cruise-sundeck.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-luxury-cruise-sundeck.jpg',
    sourceUrl: 'https://unsplash.com/photos/nile-cruiser-observation-sundeck',
    downloadUrl: 'https://images.unsplash.com/photo-1544885935-98dd03b09034?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Fadi George',
    alt: 'Private teakwood sundeck and shaded lounge on a luxury Nile cruiser sailing at sunset',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-kom-ombo-temple',
    entityType: 'experience',
    entitySlug: 'the-oberoi-zahra-luxury-nile-cruise-5d',
    filename: 'exp-gallery-kom-ombo-temple.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-kom-ombo-temple.jpg',
    sourceUrl: 'https://unsplash.com/photos/kom-ombo-temple-nile-riverside',
    downloadUrl: 'https://images.unsplash.com/photo-1566192091743-5966a6079984?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ruben Hutabarat',
    alt: 'Riverside twin sanctuary of Kom Ombo Temple overlooking the Nile River at twilight',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-winter-palace-gardens',
    entityType: 'experience',
    entitySlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    filename: 'exp-gallery-winter-palace-gardens.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-winter-palace-gardens.jpg',
    sourceUrl: 'https://unsplash.com/photos/historic-palace-gardens-estate',
    downloadUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Manuel Moreno',
    alt: 'Victorian colonial facade and sub-tropical palm gardens of the historic Winter Palace Luxor',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-valley-of-kings-monuments',
    entityType: 'experience',
    entitySlug: 'royal-upper-egypt-heritage-winter-palace-sonesta-6d',
    filename: 'exp-gallery-valley-of-kings-monuments.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-valley-of-kings-monuments.jpg',
    sourceUrl: 'https://unsplash.com/photos/valley-of-the-kings-mountains',
    downloadUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Ales Krivec',
    alt: 'Dramatic limestone cliffs and royal tomb entrances in the Valley of the Kings in Luxor',
    dimensions: { width: 1920, height: 1080 },
  },

  // ==========================================
  // Gallery Assets: International Circuits (6)
  // ==========================================
  {
    assetKey: 'exp-gallery-sheikh-zayed-mosque',
    entityType: 'experience',
    entitySlug: 'emirates-of-elegance-dubai-abu-dhabi-7d',
    filename: 'exp-gallery-sheikh-zayed-mosque.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-sheikh-zayed-mosque.jpg',
    sourceUrl: 'https://unsplash.com/photos/sheikh-zayed-grand-mosque-white-marble',
    downloadUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Saj Shafique',
    alt: 'Pristine white marble domes and reflective courtyard pools of Sheikh Zayed Grand Mosque',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-dubai-desert-twilight',
    entityType: 'experience',
    entitySlug: 'emirates-of-elegance-dubai-abu-dhabi-7d',
    filename: 'exp-gallery-dubai-desert-twilight.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-dubai-desert-twilight.jpg',
    sourceUrl: 'https://unsplash.com/photos/arabian-desert-sand-dunes-twilight',
    downloadUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'NASA',
    alt: 'Wind-swept golden desert dunes and starry purple twilight sky in the Arabian desert',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-paris-eiffel-seine',
    entityType: 'experience',
    entitySlug: 'paris-french-riviera-luxury-odyssey-8d',
    filename: 'exp-gallery-paris-eiffel-seine.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-paris-eiffel-seine.jpg',
    sourceUrl: 'https://unsplash.com/photos/eiffel-tower-seine-river-night',
    downloadUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Anthony Delanoix',
    alt: 'The Eiffel Tower illuminated above the Seine River and historic Pont Alexandre III bridge',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-french-riviera-coastline',
    entityType: 'experience',
    entitySlug: 'paris-french-riviera-luxury-odyssey-8d',
    filename: 'exp-gallery-french-riviera-coastline.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-french-riviera-coastline.jpg',
    sourceUrl: 'https://unsplash.com/photos/nice-promenade-des-anglais-azure-sea',
    downloadUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Krzysztof Kowalik',
    alt: 'The azure Mediterranean coastline and palm-lined Promenade des Anglais in Nice',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-florence-duomo-view',
    entityType: 'experience',
    entitySlug: 'italian-grand-cities-rome-florence-venice-8d',
    filename: 'exp-gallery-florence-duomo-view.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-florence-duomo-view.jpg',
    sourceUrl: 'https://unsplash.com/photos/florence-duomo-panoramic-view',
    downloadUrl: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Jonathan Körner',
    alt: 'Iconic terracotta dome of Florence Cathedral Santa Maria del Fiore at sunset',
    dimensions: { width: 1920, height: 1080 },
  },
  {
    assetKey: 'exp-gallery-venice-grand-canal',
    entityType: 'experience',
    entitySlug: 'italian-grand-cities-rome-florence-venice-8d',
    filename: 'exp-gallery-venice-grand-canal.jpg',
    localRelativePath: 'public/media-assets/experiences/exp-gallery-venice-grand-canal.jpg',
    sourceUrl: 'https://unsplash.com/photos/venice-grand-canal-palazzi',
    downloadUrl: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1920&q=80',
    provider: 'Unsplash',
    license: 'Unsplash License (Commercial and Non-Commercial Allowed)',
    photographer: 'Henrique Ferreira',
    alt: 'Venetian historic palazzi along the Grand Canal with wooden mooring posts at golden hour',
    dimensions: { width: 1920, height: 1080 },
  },
]

